CHANGELOG.md
pom.xml
sonar-delphi-plugin/pom.xml

The keepachangelog Maven plugin expects SCM information to be provided in the top-level POM, and will not generate header link implementations if it can't find it. SonarDelphi's SCM information is erroneously in `sonar-delphi-plugin/pom.xml`, not `/pom.xml`, and so running `mvn keepachangelog:release` will remove all existing header links.
This PR moves the SCM information into the correct place and slightly adjusts the changelog to match the plugin's generated output.

Provide SCM information to changelog generator

---

CHANGELOG.md
delphi-checks/src/test/java/au/com/integradev/delphi/checks/NonLinearCastCheckTest.java
delphi-frontend/src/main/java/au/com/integradev/delphi/symbol/resolve/ExpressionTypeResolver.java

When performing type resolution, SonarDelphi erroneously resolves the type of the `Create` call in this example to `TEnclosingType`:
```pascal
type
TActualType = class(TObject)
end;
TEnclosingType = class(TObject)
procedure MyProc;
end;
procedure Foo(Obj: TActualType); overload;
begin
WriteLn('Actual');
end;
procedure Foo(Obj: TEnclosingType); overload;
begin
WriteLn('Enclosing');
end;
// ...
procedure TEnclosingType.Bar;
type
TActualTypeClass = class of TActualType;
const
CActualTypes: array of TActualTypeClass = (TActualType);
begin
Foo(CActualTypes[0].Create); // Should resolve to TActualType, but resolves to TEnclosingType instead
end;
```
This bug discards any elements in a primary expression that are prior to a series of name references. and was identified from a number of false …

Fix type resolution of constructor calls on types accessed through an array access

---

delphi-checks/src/test/java/au/com/integradev/delphi/checks/StringLiteralRegularExpressionCheckTest.java
delphi-frontend/src/main/java/au/com/integradev/delphi/file/DelphiFile.java
delphi-frontend/src/main/java/au/com/integradev/delphi/preprocessor/DelphiPreprocessor.java
delphi-frontend/src/main/java/au/com/integradev/delphi/symbol/scope/DelphiScopeImpl.java
delphi-frontend/src/main/java/au/com/integradev/delphi/symbol/scope/DuplicatedDeclarationException.java
delphi-frontend/src/test/java/au/com/integradev/delphi/antlr/GrammarTest.java
delphi-frontend/src/test/java/au/com/integradev/delphi/file/DelphiFileTest.java
delphi-frontend/src/test/java/au/com/integradev/delphi/msbuild/condition/ConditionParserTest.java
delphi-frontend/src/test/java/au/com/integradev/delphi/operator/OperatorInvocableCollectorTest.java
delphi-frontend/src/test/java/au/com/integradev/delphi/symbol/QualifiedNameTest.java
delphi-frontend/src/test/java/au/com/integradev/delphi/symbol/resolve/TypeComparerTest.java
delphi-frontend/src/test/java/au/com/integradev/delphi/symbol/scope/DelphiScopeImplTest.java

This PR fixes [15 SonarCloud issues](https://sonarcloud.io/project/issues?resolved=false&rules=java%3AS112%2Cjava%3AS5778&types=CODE_SMELL&id=integrated-application-development_sonar-delphi&open=AYuyR9CGfd4wpt45YCY6) for the following rules:
- [Only one method invocation is expected when testing runtime exceptions](https://sonarcloud.io/organizations/integrated-application-development/rules?open=java%3AS5778&rule_key=java%3AS5778)
- [Generic exceptions should never be thrown](https://sonarcloud.io/organizations/integrated-application-development/rules?open=java%3AS112&rule_key=java%3AS112)

Fix Sonar issues for dedicated exceptions and overloaded test lambdas

---

.github/ISSUE_TEMPLATE/engine_improvement.yml

This PR adds a "Rules API" category for the Engine Improvement issue template. This helps fill the gap of requests that improve the API.

Add rules API option to Engine Improvement issue template

---

README.md
its/pom.xml
pom.xml

Because integration tests spin up a SonarQube server, they share SonarQube's Java requirements.
SonarQube only runs under Java 17 (no other versions are supported), meaning that the integration tests require the developer to be running JDK 17 *exactly*.
This is a weird/inconvenient limitation to impose on contributors.

Skip integration tests by default

---

delphi-frontend/src/main/java/au/com/integradev/delphi/symbol/SymbolTableBuilder.java

Resolves #86 using the discussed approach, in which the scopes of class reference types are not traversed when finding inline declarations.

Exclude class reference types from inline declaration search

---

.github/workflows/build.yml

This PR adds a step to the build workflow to save the generated sonar-delphi-plugin jar as an artifact. This saves having to check out the repository and run a `mvn install` when retrieving a specific version of the jar.

Upload plugin jar artifact in build workflow

---

delphi-checks/src/main/resources/org/sonar/l10n/delphi/rules/community-delphi/VisibilityKeywordIndentation.html

The rule description erroneously refered to 'trailing' whitespace, but it checks indentation which is actually leading whitespace.

Update `VisibilityKeywordIndentation` to refer to 'leading' whitespace

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/docs_improvement.yml
.github/ISSUE_TEMPLATE/engine_improvement.yml
.github/ISSUE_TEMPLATE/inquiry.yml
.github/ISSUE_TEMPLATE/new_rule.yml
.github/ISSUE_TEMPLATE/rule_improvement.yml

This PR modifies the issue templates to:
- Remove the `[Rule Type]:` prefix
- Use more descriptive labels (in particular the new `rule`, `feature`, and `engine` labels)

Update issue templates to use new labels

---

CHANGELOG.md
delphi-checks/src/main/java/au/com/integradev/delphi/checks/AbstractCastCheck.java
delphi-checks/src/main/java/au/com/integradev/delphi/checks/CastAndFreeCheck.java
delphi-checks/src/main/java/au/com/integradev/delphi/utils/CastUtils.java
delphi-checks/src/main/resources/org/sonar/l10n/delphi/rules/community-delphi/CastAndFree.html
delphi-checks/src/test/java/au/com/integradev/delphi/checks/CastAndFreeCheckTest.java

Fixes #115 by using type and symbol table information to evaluate casts in the CastAndFree rule.
Currently, our cast logic is implemented entirely in the AbstractCast base rule, and is only available to descendants of said class. This PR extracts the cast detection logic from AbstractCast into a new utility, CastUtils, which parses primary expressions and binary expressions into cast objects. CastAndFree was then reimplemented using CastUtils.

Use semantic analysis in CastAndFree

---

CHANGELOG.md
delphi-frontend/src/main/java/au/com/integradev/delphi/msbuild/DelphiProjectHelper.java
delphi-frontend/src/test/java/au/com/integradev/delphi/msbuild/DelphiProjectHelperTest.java
sonar-delphi-plugin/src/main/java/au/com/integradev/delphi/DelphiSensor.java
sonar-delphi-plugin/src/test/java/au/com/integradev/delphi/DelphiSensorTest.java

This PR adds support for SonarDelphi to recognise `sonar.tests` as test code and scan accordingly.
Test code in SonarDelphi is usually identified using the `sonar.delphi.testAttribute` or `sonar.delphi.testType` properties.
This is different to the normal Sonar approach, in which units can also be specified as test units by specifying them in `sonar.tests` instead of `sonar.sources`. Currently, SonarDelphi disregards any files provided through the `sonar.tests` option.

Include test files in scan

---

CHANGELOG.md
delphi-checks/src/main/java/au/com/integradev/delphi/checks/UnusedFieldCheck.java
delphi-checks/src/main/java/au/com/integradev/delphi/checks/UnusedPropertyCheck.java
delphi-checks/src/main/java/au/com/integradev/delphi/checks/UnusedRoutineCheck.java
delphi-checks/src/main/resources/org/sonar/l10n/delphi/rules/community-delphi/UnusedField.html
delphi-checks/src/main/resources/org/sonar/l10n/delphi/rules/community-delphi/UnusedProperty.html
delphi-checks/src/main/resources/org/sonar/l10n/delphi/rules/community-delphi/UnusedRoutine.html
delphi-checks/src/test/java/au/com/integradev/delphi/checks/UnusedFieldCheckTest.java
delphi-checks/src/test/java/au/com/integradev/delphi/checks/UnusedPropertyCheckTest.java
delphi-checks/src/test/java/au/com/integradev/delphi/checks/UnusedRoutineCheckTest.java
delphi-frontend/src/main/antlr3/au/com/integradev/delphi/antlr/Delphi.g
delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/ast/node/AttributeListNodeImpl.java
delphi-frontend/src/main/java/au/com/integradev/delphi/symbol/declaration/PropertyNameDeclarationImpl.java
delphi-frontend/src/main/java/au/com/integradev/delphi/symbol/declaration/RoutineNameDeclarationImpl.java
delphi-frontend/src/main/java/au/com/integradev/delphi/type/factory/TypeFactoryImpl.java
delphi-frontend/src/main/java/org/sonar/plugins/communitydelphi/api/ast/AttributeListNode.java
delphi-frontend/src/main/java/org/sonar/plugins/communitydelphi/api/symbol/declaration/PropertyNameDeclaration.java
delphi-frontend/src/main/java/org/sonar/plugins/communitydelphi/api/symbol/declaration/RoutineNameDeclaration.java
delphi-frontend/src/test/java/au/com/integradev/delphi/symbol/declaration/RoutineNameDeclarationTest.java
delphi-frontend/src/test/java/au/com/integradev/delphi/symbol/scope/RoutineScopeImplTest.java

Routines, properties, or fields that are annotated with an attribute are generally done so because they will be accessed at runtime via RTTI. This PR fixes #113 by excluding these members from UnusedRoutine, UnusedProperty, and UnusedField.
A couple of changes have been made to the API to facilitate this change:
- `AttributeListNode` now has a `getAttributeTypes` method that returns the list of attributes as their types
- `PropertyNameDeclaration` now has a `getAttributeTypes` method that returns a list of the types of each annotated attribute
- `RoutineNameDeclaration` now has a `getAttributeTypes` method that returns a list of the types of each annotated attribute

Exclude routines, properties, and fields with attributes from dead code checks

---

CHANGELOG.md
delphi-frontend/src/main/antlr3/au/com/integradev/delphi/antlr/Delphi.g
delphi-frontend/src/test/java/au/com/integradev/delphi/antlr/GrammarTest.java
delphi-frontend/src/test/java/au/com/integradev/delphi/symbol/scope/DelphiScopeImplTest.java
delphi-frontend/src/test/resources/au/com/integradev/delphi/grammar/FullWidthNumeralBeforeIdentifier.pas
delphi-frontend/src/test/resources/au/com/integradev/delphi/grammar/UnicodeIdentifiers.pas

Fixes #125
The Unicode-aware case-insensitive identifier comparison that we are currently performing doesn't _perfectly_ match the Delphi compiler, but @Cirras and I decided it wasn't worth trying to match this unspecified behaviour. Instead, I documented the situation with some tests and comments in `DelphiScopeImplTest`

Add support Unicode identifiers

---

CHANGELOG.md
delphi-checks/src/main/java/au/com/integradev/delphi/checks/AbstractCastCheck.java
delphi-checks/src/main/java/au/com/integradev/delphi/checks/PlatformDependentCastCheck.java

The current standard behavior around flagging hard casts is to highlight the argument list in the issue.
```
ShortInt(123);
^^^^^
```
This can be very confusing in the case of nested hard casts, and you might erroneously think the issue applies to the inner cast.
Consistently highlighting the whole cast expression would make this clearer:
```
ShortInt(123);
^^^^^^^^^^^^^
```
This PR changes the behavior to highlight the whole hard cast expression in the following rules:
- `UnicodeToAnsiCast`
- `CharacterToCharacterPointerCastCheck`
- `NonLinearCastCheck`
- `RedundantCastCheck`
- `PlatformDependentCast`

Highlight the whole hard cast expression when reporting issues

---

CHANGELOG.md
delphi-checks/src/main/java/au/com/integradev/delphi/checks/UnusedConstantCheck.java
delphi-checks/src/main/java/au/com/integradev/delphi/checks/UnusedFieldCheck.java
delphi-checks/src/main/java/au/com/integradev/delphi/checks/UnusedGlobalVariableCheck.java
delphi-checks/src/main/java/au/com/integradev/delphi/checks/UnusedPropertyCheck.java
delphi-checks/src/main/java/au/com/integradev/delphi/checks/UnusedRoutineCheck.java
delphi-checks/src/main/java/au/com/integradev/delphi/checks/UnusedTypeCheck.java
delphi-checks/src/test/java/au/com/integradev/delphi/checks/UnusedConstantCheckTest.java
delphi-checks/src/test/java/au/com/integradev/delphi/checks/UnusedFieldCheckTest.java
delphi-checks/src/test/java/au/com/integradev/delphi/checks/UnusedGlobalVariableCheckTest.java
delphi-checks/src/test/java/au/com/integradev/delphi/checks/UnusedPropertyCheckTest.java
delphi-checks/src/test/java/au/com/integradev/delphi/checks/UnusedRoutineCheckTest.java
delphi-checks/src/test/java/au/com/integradev/delphi/checks/UnusedTypeCheckTest.java
delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/ast/node/TypeDeclarationNodeImpl.java
delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/ast/node/TypeSectionNodeImpl.java
delphi-frontend/src/main/java/org/sonar/plugins/communitydelphi/api/ast/TypeDeclarationNode.java
delphi-frontend/src/main/java/org/sonar/plugins/communitydelphi/api/ast/TypeSectionNode.java

This new property excludes public API (declared in the interface section with public visibility).
This primarily caters to libraries, which have large public API surfaces that are intended for consumers of the library.
Closes #106

Add `excludeApi` property to the `Unused*` rules

---

CHANGELOG.md

Changelog entries describing the API methods introduced in #121 were accidentally removed in a5d88a010ac62f6c22e2d66c5bba56d1111977ee. This PR re-adds those entries.

Reference new attribute-related API methods in changelog

---

delphi-checks/src/main/java/au/com/integradev/delphi/checks/UnusedConstantCheck.java
delphi-checks/src/main/java/au/com/integradev/delphi/checks/UnusedFieldCheck.java
delphi-checks/src/main/java/au/com/integradev/delphi/checks/UnusedGlobalVariableCheck.java
delphi-checks/src/main/java/au/com/integradev/delphi/checks/UnusedPropertyCheck.java
delphi-checks/src/main/java/au/com/integradev/delphi/checks/UnusedRoutineCheck.java
delphi-checks/src/main/java/au/com/integradev/delphi/checks/UnusedTypeCheck.java

A minor oversight in #137 - we didn't provide a default value to SonarQube for the new `excludeApi` properties.
This PR provides a default value of "false" for all `excludeApi` rule properties, making that default value explicit in the SonarQube UI and also making it clearer that the property is a boolean value.

Provide default value of `excludeApi` properties to SonarQube

---

CHANGELOG.md
delphi-frontend/src/main/java/au/com/integradev/delphi/symbol/scope/DelphiScopeImpl.java
delphi-frontend/src/test/java/au/com/integradev/delphi/executor/DelphiSymbolTableExecutorTest.java
delphi-frontend/src/test/resources/au/com/integradev/delphi/symbol/helpers/WeakAliasHelper.pas

Internally, we map `Type` -> `HelperType` when doing helper lookups in a given scope.
The analyzer models weak alias types by generating a transparent wrapper around the aliased type. It looks and behaves exactly like the aliased type, but the two type objects are not **equal** to each other.
The source of truth about a type's identity is the image, so the solution here is to simply map `<type image>` -> `HelperType` instead.
Fixes #104 and #108.

Fix name resolution failures around type helpers for weak aliases

---

CHANGELOG.md
delphi-checks/src/test/java/au/com/integradev/delphi/checks/UnusedLocalVariableCheckTest.java
delphi-frontend/src/main/java/au/com/integradev/delphi/type/intrinsic/IntrinsicArgumentMatcher.java
delphi-frontend/src/main/java/au/com/integradev/delphi/type/intrinsic/IntrinsicsInjector.java
delphi-frontend/src/test/java/au/com/integradev/delphi/type/intrinsic/IntrinsicArgumentMatcherTest.java

This PR adds a new `TYPED_POINTER` overload to the `Inc` and `Dec` intrinsic signatures.
Fixes #141.

Fix name resolution failures when `Inc`/`Dec` are invoked on pointers

---

delphi-checks/src/main/resources/org/sonar/l10n/delphi/rules/community-delphi/VariableName.html

Fixes #96 by rephrasing the VariableName description, emphasising that the rule enforces naming conventions for both local and global variables.

Clarify wording of VariableName description

---

CHANGELOG.md
delphi-frontend/src/main/java/au/com/integradev/delphi/symbol/resolve/NameResolver.java

This PR restores the declaration information in "ambiguous declarations" warnings.
Example output:
```
WARN: Ambiguous declarations could not be resolved
[Occurrence] Length [11399,16] <Data.DBXCommon>
[Declaration] Routine Length, line 0, params = 1 <System>
[Declaration] Routine Length, line 0, params = 1 <System>
```

Fix missing information in "ambiguous declarations" warnings

---

CHANGELOG.md
delphi-frontend/src/main/java/au/com/integradev/delphi/symbol/resolve/InvocationCandidate.java
delphi-frontend/src/main/java/au/com/integradev/delphi/symbol/resolve/InvocationResolver.java
delphi-frontend/src/main/java/au/com/integradev/delphi/symbol/resolve/TypeComparer.java
delphi-frontend/src/main/java/au/com/integradev/delphi/type/intrinsic/IntrinsicArgumentMatcher.java
delphi-frontend/src/main/java/au/com/integradev/delphi/type/intrinsic/IntrinsicReturnType.java
delphi-frontend/src/main/java/au/com/integradev/delphi/type/intrinsic/IntrinsicsInjector.java
delphi-frontend/src/test/java/au/com/integradev/delphi/symbol/resolve/InvocationResolverTest.java
delphi-frontend/src/test/java/au/com/integradev/delphi/symbol/resolve/TypeComparerTest.java
delphi-frontend/src/test/java/au/com/integradev/delphi/type/intrinsic/IntrinsicArgumentMatcherTest.java

This PR:
- Improves type comparisons between text types
- `AnsiString` -> `UnicodeString` conversions are preferred over
`UnicodeString` -> `AnsiString` conversions.
- `UnicodeString` -> `Variant` conversions are preferred over
`UnicodeString` -> `AnsiString` conversions.
- `AnsiString` -> `UnicodeString` conversions are preferred over
`AnsiString` -> `Variant` conversions.
- ⭐ discovered while fixing the `Concat` intrinsic, which was originally going to have `(AnsiString, AnsiString)` and `(UnicodeString, UnicodeString)` overloads to disambiguate
- Improves type conversions from character pointers to strings
- `PAnsiChar` -> `AnsiString` conversions are preferred over `PAnsiChar` -> `ShortString`.
- ⭐ important for the `Length` intrinsic, which has `AnsiString` and `ShortString` …

Improve behavior of various intrinsic routines

---

delphi-frontend/src/main/java/au/com/integradev/delphi/operator/OperatorInvocableCollector.java
delphi-frontend/src/test/java/au/com/integradev/delphi/executor/DelphiSymbolTableExecutorTest.java
delphi-frontend/src/test/resources/au/com/integradev/delphi/symbol/operators/BinaryOperatorIntrinsics.pas

Intrinsic operator overloads were not being collected for the return types of procedural operands.
This was broken by commit c151981.

Fix type resolution errors on expressions with procedural operands

---

prepare-release.sh

This PR fixes a minor issue in the release process.
The `sonar.delphi.version` property in `delphi-custom-rules-example` wasn't being updated in `prepare-release`.

Update `sonar.delphi.version` property in `prepare-release`

---

CHANGELOG.md
delphi-frontend/src/main/java/au/com/integradev/delphi/type/intrinsic/IntrinsicReturnType.java
delphi-frontend/src/test/java/au/com/integradev/delphi/type/intrinsic/IntrinsicReturnTypeTest.java

This PR ties up some loose ends around intrinsics.
There are still a few issues around intrinsic return type inference:
* `Copy` wasn't returning string types for character pointer or variant arguments
* `Concat` wasn't widening character types to string types (for single-character string literals)
Also, I added tests for the `IntrinsicReturnType` meta-types.

Tidy up intrinsic return type inference

---

delphi-checks/pom.xml
delphi-checks/src/test/java/au/com/integradev/delphi/checks/CheckMetadataTest.java
delphi-frontend/pom.xml
delphi-frontend/src/main/java/org/sonar/plugins/communitydelphi/api/check/ScopeMetadataLoader.java
pom.xml

`json-simple` is unmaintained and has an annoying API that encourages unsafe casts.
It also pulls in a vulnerable version of junit 4 as a compile dependency, generating meaningless noise from Sonatype Lift.
(**note:** there is no actual vulnerability, junit wasn't even supposed to be a compile dependency in `json-simple`)

Migrate from `json-simple` to `gson`

---

CHANGELOG.md
delphi-frontend/src/main/antlr3/au/com/integradev/delphi/antlr/Delphi.g
delphi-frontend/src/test/java/au/com/integradev/delphi/antlr/GrammarTest.java
docs/delphi-custom-rules-example/pom.xml
pom.xml
sonar-delphi-plugin/pom.xml

This PR upgrades all of the maven plugin dependencies.
It fixes the following error that occurred during tests:
`"Corrupted STDOUT by directly writing to native stream in forked JVM"`
This error was masking 2 failing tests in `GrammarTest`, one of which was a minor v1.1.0 regression introduced in #130.
(@zaneduffield, can you follow up and push a fix for that second failing test to this PR?)

Upgrade maven plugins

---

CHANGELOG.md
delphi-frontend/src/main/java/au/com/integradev/delphi/symbol/scope/FileScopeImpl.java

Delphi `requires` clauses permit duplicate units, e.g. a `.dpk` with the following code compiles:
```delphi
package MyPackage;
requires
rtl,
vcl,
rtl;
end.
```
SonarDelphi does not currently permit this. This PR adds a special case to `DelphiScopeImpl::addDeclaration` that catches the duplicate declaration exception and logs a warning instead if the declaration is a unit import.
Note that this change also "permits" duplicate imports in normal uses clauses, but since this is a compilation error anyway I think it's the most practical way to solve this problem. Happy to hear other thoughts.

Downgrade duplicate unit import error to warning

---

CHANGELOG.md
delphi-frontend/src/main/java/au/com/integradev/delphi/compiler/PredefinedConditionals.java
delphi-frontend/src/test/java/au/com/integradev/delphi/compiler/PredefinedConditionalsTest.java

This PR adds support for the `LLVM` symbol, which is defined on LLVM-based toolchains from Delphi 12 onward.
Closes #160.

Define the `LLVM` symbol on LLVM-based toolchains

---

CHANGELOG.md
delphi-frontend/src/main/java/au/com/integradev/delphi/compiler/PredefinedConditionals.java
delphi-frontend/src/test/java/au/com/integradev/delphi/compiler/PredefinedConditionalsTest.java

This PR adds support for the `IOSSIMULATOR` symbol, which is defined on the `DCCIOSSIMARM64` toolchain.
Closes #163.

Define the `IOSSIMULATOR` symbol on `DCCIOSSIMARM64`

---

pom.xml

Our integration tests, which only run in a CI environment, use SonarSource's open-source [sonar-orchestrator](https://github.com/SonarSource/orchestrator) library to orchestrate a SonarQube server.
These tests are currently failing, seemingly due to SonarSource changing the Artifactory server the orchestrator communicates with to require SonarSource authentication ([see here](https://sonarsource.atlassian.net/browse/SONAR-21476)). We have made [an inquiry](https://community.sonarsource.com/t/community-plugins-can-no-longer-make-requests-to-jfrog-via-the-orchestrator-library/107955), and in the meantime we will disable the ITs so our CI checks don't give an inaccurate impression of SonarDelphi's functionality.

Disable integration tests

---

CHANGELOG.md
delphi-checks/src/main/java/au/com/integradev/delphi/checks/AbstractFormResourceCheck.java
delphi-checks/src/main/java/au/com/integradev/delphi/checks/CheckList.java
delphi-checks/src/main/java/au/com/integradev/delphi/checks/FormDfmCheck.java
delphi-checks/src/main/java/au/com/integradev/delphi/checks/FormFmxCheck.java
delphi-checks/src/main/resources/org/sonar/l10n/delphi/rules/community-delphi/FormDfm.html
delphi-checks/src/main/resources/org/sonar/l10n/delphi/rules/community-delphi/FormDfm.json
delphi-checks/src/main/resources/org/sonar/l10n/delphi/rules/community-delphi/FormFmx.html
delphi-checks/src/main/resources/org/sonar/l10n/delphi/rules/community-delphi/FormFmx.json
delphi-checks/src/test/java/au/com/integradev/delphi/checks/FormDfmCheckTest.java
delphi-checks/src/test/java/au/com/integradev/delphi/checks/FormFmxCheckTest.java
delphi-frontend/src/main/java/au/com/integradev/delphi/preprocessor/directive/CompilerDirectiveParserImpl.java
delphi-frontend/src/main/java/au/com/integradev/delphi/preprocessor/directive/ResourceDirectiveImpl.java
delphi-frontend/src/main/java/org/sonar/plugins/communitydelphi/api/directive/ResourceDirective.java
delphi-frontend/src/test/java/au/com/integradev/delphi/preprocessor/directive/CompilerDirectiveParserTest.java

**New rules:**
* `FormDfm`: “VCL forms and frames should have a .dfm form file”
* `FormFmx`: “FireMonkey forms and frames should have a .fmx form file”
Neither rule is included in `Sonar way`.
**Compiler directives API:**
* The `RESOURCE` directive is modeled with a new `ResourceDirective` type.

Add checks to detect forms/frames without accompanying resource files

---

CHANGELOG.md
delphi-checks/src/main/java/au/com/integradev/delphi/checks/MixedNamesCheck.java
delphi-checks/src/test/java/au/com/integradev/delphi/checks/MixedNamesCheckTest.java
delphi-frontend/src/main/java/au/com/integradev/delphi/type/intrinsic/IntrinsicsInjector.java

As described in #102, the jury is out on the casing of the `WriteLn` and `ReadLn` intrinsics - the debug information says `Ln`, while the documentation and the IDE say `ln`. For the purposes of the MixedNames check, SonarDelphi currently only accepts `WriteLn` and `ReadLn`.
This PR amends the MixedNames check to also accept the `ln` casing, and adds an additional (only partially documented) overload to the `ReadLn` intrinsic that does not include a file parameter. This was causing SonarDelphi to fail to resolve `Readln`and accidentally correctly accept it in some cases.
Fixes #102

Support alternative casings for `WriteLn` and `ReadLn`

---

CHANGELOG.md
delphi-frontend/src/main/java/au/com/integradev/delphi/symbol/resolve/NameResolver.java
delphi-frontend/src/main/java/au/com/integradev/delphi/symbol/scope/DelphiScopeImpl.java
delphi-frontend/src/test/java/au/com/integradev/delphi/executor/DelphiSymbolTableExecutorTest.java
delphi-frontend/src/test/resources/au/com/integradev/delphi/symbol/ShadowedImportedUnitName.pas
delphi-frontend/src/test/resources/au/com/integradev/delphi/symbol/shadowedImports/ConstShadowingImport.pas
delphi-frontend/src/test/resources/au/com/integradev/delphi/symbol/shadowedImports/InterfaceImportShadowedInImplementation.pas
delphi-frontend/src/test/resources/au/com/integradev/delphi/symbol/shadowedImports/InterfaceImportShadowedLater.pas
delphi-frontend/src/test/resources/au/com/integradev/delphi/symbol/shadowedImports/RoutineShadowingImport.pas
delphi-frontend/src/test/resources/au/com/integradev/delphi/symbol/shadowedImports/ShadowedImplementationImport.pas
delphi-frontend/src/test/resources/au/com/integradev/delphi/symbol/shadowedImports/ShadowedName.pas
delphi-frontend/src/test/resources/au/com/integradev/delphi/symbol/shadowedImports/TypeShadowingImport.pas
delphi-frontend/src/test/resources/au/com/integradev/delphi/symbol/shadowedImports/UnshadowedImplementationImport.pas
delphi-frontend/src/test/resources/au/com/integradev/delphi/symbol/shadowedImports/VarShadowingImport.pas

In Delphi, symbols can be declared with the same name as an imported unit. The behaviour seems to be that unit imports are shadowed by any subsequent declaration, but shadow all previous declarations. This PR implements this behaviour in SonarDelphi, which currently fails if a file-level symbol is declared with the same name as a unit import.
Fixes #161

Allow unit imports to be shadowed

---

CHANGELOG.md
delphi-checks/src/main/resources/org/sonar/l10n/delphi/rules/community-delphi/EmptyRoutine.html

The EmptyRoutine description currently gives the impression that *any* routine with an explanatory comment is excluded from the check. The actual behaviour is that routines have to both have a comment *and* be a valid exclusion to be excluded.
This PR updates the description to agree with the behaviour of the check.

Correct inaccuracies in EmptyRoutine description

---

delphi-checks/src/main/java/au/com/integradev/delphi/checks/FormatArgumentTypeCheck.java
delphi-checks/src/main/resources/org/sonar/l10n/delphi/rules/community-delphi/FormatArgumentType.html
delphi-checks/src/main/resources/org/sonar/l10n/delphi/rules/community-delphi/FormatStringValid.html
delphi-checks/src/test/java/au/com/integradev/delphi/checks/FormatArgumentTypeCheckTest.java

This PR fixes two problems with the FormatArgumentType rule:
* Function invocations returning a value of an acceptable type were incorrectly highlighted as an issue
* Variants were incorrectly not considered an acceptable type for the `%s` format specifier
Bundled with this PR is a minor wording change to the FormatStringValid rule to clarify some Delphi behaviour.

Handle function return types and Variants in FormatArgumentType

---

CHANGELOG.md
delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/ast/token/DelphiTokenImpl.java
delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/ast/visitors/SonarSymbolTableVisitor.java
delphi-frontend/src/main/java/au/com/integradev/delphi/symbol/SymbolicNode.java
delphi-frontend/src/main/java/org/sonar/plugins/communitydelphi/api/token/DelphiToken.java
delphi-frontend/src/test/java/au/com/integradev/delphi/executor/DelphiSymbolTableExecutorTest.java
delphi-frontend/src/test/java/au/com/integradev/delphi/symbol/scope/UnknownScopeImplTest.java
delphi-frontend/src/test/resources/au/com/integradev/delphi/symbol/includes/Includes.pas
delphi-frontend/src/test/resources/au/com/integradev/delphi/symbol/includes/MyInclude.inc

This PR fixes #174 by excluding all symbols that are declared in an include file from the Sonar symbol table. There are two properties of symbols declared in include files that make them inappropriate to add to the Sonar symbol table:
- If more than one symbol is declared, both symbol declarations have the same text range, which is problematic as Sonar uses the declaration text range as the unique key for the symbol.
- If a symbol is both declared and referenced in the include file, an exception is raised because both the declaration and reference are overlapping.
Unfortunately this means that symbols declared in include files will not have symbol table information associated with them in the SonarQube UI, but in the grand scheme of things this isn't too much of a problem.
Note that this …

Fix symbol table executor failures on include directives with declarations and references

---

CHANGELOG.md
docs/CUSTOM_RULES_101.md
docs/delphi-custom-rules-example/pom.xml
sonar-delphi-plugin/pom.xml

This PR adds support for the new on-demand plugin loading feature in SonarQube 10.4.
See: [The SonarScanners download only required 3rd-party plugins](https://community.sonarsource.com/t/the-sonarscanners-download-only-required-3rd-party-plugins/108156)

Enable on-demand plugin downloading

---

README.md
delphi-checks/src/main/resources/org/sonar/l10n/delphi/rules/community-delphi/AddressOfCharacterData.json
delphi-checks/src/main/resources/org/sonar/l10n/delphi/rules/community-delphi/BeginEndRequired.json
delphi-checks/src/main/resources/org/sonar/l10n/delphi/rules/community-delphi/CharacterToCharacterPointerCast.json
delphi-checks/src/main/resources/org/sonar/l10n/delphi/rules/community-delphi/ConstructorWithoutInherited.json
delphi-checks/src/main/resources/org/sonar/l10n/delphi/rules/community-delphi/DestructorWithoutInherited.json
delphi-checks/src/main/resources/org/sonar/l10n/delphi/rules/community-delphi/EmptyFinallyBlock.json
delphi-checks/src/main/resources/org/sonar/l10n/delphi/rules/community-delphi/ExplicitTObjectInheritance.json
delphi-checks/src/main/resources/org/sonar/l10n/delphi/rules/community-delphi/FormatArgumentCount.html
delphi-checks/src/main/resources/org/sonar/l10n/delphi/rules/community-delphi/FormatArgumentType.json
delphi-checks/src/main/resources/org/sonar/l10n/delphi/rules/community-delphi/FreeAndNilTObject.json
delphi-checks/src/main/resources/org/sonar/l10n/delphi/rules/community-delphi/GotoStatement.json
delphi-checks/src/main/resources/org/sonar/l10n/delphi/rules/community-delphi/IfThenShortCircuit.json
delphi-checks/src/main/resources/org/sonar/l10n/delphi/rules/community-delphi/ImplicitDefaultEncoding.json
delphi-checks/src/main/resources/org/sonar/l10n/delphi/rules/community-delphi/IndexLastListElement.html
delphi-checks/src/main/resources/org/sonar/l10n/delphi/rules/community-delphi/IndexLastListElement.json
delphi-checks/src/main/resources/org/sonar/l10n/delphi/rules/community-delphi/NilComparison.json
delphi-checks/src/main/resources/org/sonar/l10n/delphi/rules/community-delphi/NoSonar.json
delphi-checks/src/main/resources/org/sonar/l10n/delphi/rules/community-delphi/StringListDuplicates.json
delphi-checks/src/main/resources/org/sonar/l10n/delphi/rules/community-delphi/WithStatement.json

This PR contains a number of miscellaneous metadata improvements:
- Rewords FormatArgumentType title to be more consistent with FormatArgumentCount
- Adds a reference to FormatArgumentType to the README
- Removes `.` from the end of the IndexLastListElement and AddressOfCharacterData rule titles
- Adds an example to IndexLastListElement
- Fix an incorrect diff and do partial rewording in FormatArgumentCount

Improve rule metadata

---

CHANGELOG.md
delphi-checks/src/main/java/au/com/integradev/delphi/checks/FormatArgumentTypeCheck.java
delphi-checks/src/main/resources/org/sonar/l10n/delphi/rules/community-delphi/FormatArgumentType.html
delphi-checks/src/test/java/au/com/integradev/delphi/checks/FormatArgumentTypeCheckTest.java

`Format`'s (undocumented) behaviour seems to be that static char arrays are allowed as an argument to the `%s` (string) specifier, where they are interpreted as null-terminated strings. Dynamic char arrays do not have this ability, but can be printed by casting to `PChar` instead.
This PR updates FormatArgumentType to match this behaviour.

Accept static char arrays for '%s' in FormatArgumentType

---

CHANGELOG.md
delphi-checks/src/main/java/au/com/integradev/delphi/checks/DigitGroupingCheck.java
delphi-checks/src/test/java/au/com/integradev/delphi/checks/DigitGroupingCheckTest.java
delphi-frontend/src/main/antlr3/au/com/integradev/delphi/antlr/Delphi.g
delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/ast/node/IdentifierNodeImpl.java
delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/ast/node/IntegerLiteralNodeImpl.java
delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/ast/node/RealLiteralNodeImpl.java
delphi-frontend/src/test/java/au/com/integradev/delphi/antlr/GrammarTest.java
delphi-frontend/src/test/resources/au/com/integradev/delphi/grammar/AmpersandNumericLiterals.pas

Fixes #173 by accepting and discarding any ampersands before a number literal.
Some caveats:
- This occurs during parsing, not lexing (which might be more correct). This is because our ampersand handling for identifiers is in the parser. 
- This grammar will technically support whitespace between the ampersands and the number literals. I don't think this should be an issue as there's no ambiguity with any other language constructs.

Support ampersand-prefixed number literals

---

its/src/test/java/au/com/integradev/delphi/IntegrationTestSuite.java
pom.xml

Integration tests were disabled in #170.
The upstream issue in the Orchestrator library is now fixed.

Upgrade Orchestrator and re-enable integration tests

---

.github/workflows/build.yml
.github/workflows/format.yml
.github/workflows/release.yml
.github/workflows/sonar.yml

This PR fixes a bunch of CI warnings due to Node 16 being deprecated.

Bump versions of workflow dependencies

---

.github/workflows/release.yml

This PR fixes warnings in the release workflow by removing our dependency on `battila7/get-version-action`.
The `get-version-action` action has a couple of issues:
- It uses the deprecated `set-output` (https://github.com/battila7/get-version-action/issues/22)
- It runs on the deprecated Node 12 (https://github.com/battila7/get-version-action/issues/18)
This action doesn't do much though, and our use-case can be trivially satisfied using `GITHUB_REF_NAME`.

Remove dependency on `battila7/get-version-action`

---

pom.xml

SonarSource has released a patch to fix an issue where Orchestrator was pulling the wrong SonarQube version for the `LATEST_RELEASE` alias (which we use).

Bump Orchestrator to v4.7.1.1872

---

CHANGELOG.md
delphi-frontend/src/main/antlr3/au/com/integradev/delphi/antlr/Delphi.g
delphi-tokens-generator-maven-plugin/src/main/java/au/com/integradev/delphi/DelphiTokensGeneratorMojo.java

This PR implements token deprecation in `DelphiTokenType` generation.
Any token suffixed with `__deprecated` in the grammar will be generated with `@Deprecated(forRemoval = true)`.
Additionally, the `AMPERSAND` token (which prompted this change) has been marked as deprecated.

Implement token deprecation

---

CHANGELOG.md
delphi-frontend/src/main/antlr3/au/com/integradev/delphi/antlr/Delphi.g

This is a silly mistake that we inherited in the Delphi grammar.
We've been defining our imaginary tokens with actual values, and not thinking much of it. However, this technically means that they could be matched in source code by the lexer and wreak all sorts of havoc.
Declaring imaginary tokens in a `tokens` block is a clean and easy way of preventing them from ever being matched.

Make imaginary tokens unmatchable

---

delphi-tokens-generator-maven-plugin/pom.xml
delphi-tokens-generator-maven-plugin/src/main/java/au/com/integradev/delphi/DelphiTokensGenerator.java
delphi-tokens-generator-maven-plugin/src/main/java/au/com/integradev/delphi/DelphiTokensGeneratorMojo.java
delphi-tokens-generator-maven-plugin/src/test/java/au/com/integradev/delphi/DelphiTokensGeneratorTest.java

This PR:
- splits `DelphiTokensGenerator` from `DelphiTokensGeneratorMojo`
- adds unit tests for `DelphiTokensGenerator`
- fixes a bug where tokens from the `Delphi.tokens` would not be recognized if their names contained numbers
- adds `@SuppressWarnings("removal")` to the entire `DelphiTokenTypeFactory` instead of the 2 methods within it
- only adds `@SuppressWarnings("removal")` to `DelphiTokenTypeFactory` if 1 or more tokens are deprecated

Refactor `delphi-tokens-generator-maven-plugin` and add unit tests

---

CHANGELOG.md
delphi-checks/src/main/java/au/com/integradev/delphi/checks/AbstractFormatArgumentCheck.java
delphi-checks/src/main/java/au/com/integradev/delphi/checks/StringLiteralRegularExpressionCheck.java
delphi-frontend/src/main/antlr3/au/com/integradev/delphi/antlr/Delphi.g
delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/ast/node/TextLiteralNodeImpl.java
delphi-frontend/src/main/java/org/sonar/plugins/communitydelphi/api/ast/TextLiteralNode.java
delphi-frontend/src/test/java/au/com/integradev/delphi/antlr/GrammarTest.java
delphi-frontend/src/test/java/au/com/integradev/delphi/antlr/ast/node/TextLiteralNodeImplTest.java
delphi-frontend/src/test/resources/au/com/integradev/delphi/grammar/MultilineInvalidButAcceptedStrings.pas
delphi-frontend/src/test/resources/au/com/integradev/delphi/grammar/MultilineLookalikeStrings.pas
delphi-frontend/src/test/resources/au/com/integradev/delphi/grammar/MultilineStrings.pas

This PR:
- adds support for the multiline strings from Delphi 12
- deprecates `getImageWithoutQuotes` in favor of `getValue`
- improves the evaluation of character escapes
- improves test coverage for `TextLiteralNodeImpl`
Closes #80.

Implement multiline strings

---

CHANGELOG.md
delphi-checks/src/main/java/au/com/integradev/delphi/checks/PublicFieldCheck.java
delphi-checks/src/test/java/au/com/integradev/delphi/checks/PublicFieldCheckTest.java
delphi-frontend/src/main/antlr3/au/com/integradev/delphi/antlr/Delphi.g

This PR fixes a null pointer exception that occurs when `PublicFieldCheck` encounters an anonymous record. 
I've also bundled in the removal of a dead rule from the grammar.

Fix null reference in PublicField when encountering anonymous records

---

CHANGELOG.md
delphi-checks/src/main/java/au/com/integradev/delphi/checks/InheritedMethodWithNoCodeCheck.java
delphi-checks/src/test/java/au/com/integradev/delphi/checks/InheritedMethodWithNoCodeCheckTest.java

When traversing a routine's inheritance tree, InheritedMethodNoCode currently does not distinguish between class routines and member routines. This can cause the wrong routine to be chosen if a class routine with the same name and number of parameters exists in the inheritance tree.
This PR fixes this issue by filtering out non-callable routines.

Fix InheritedMethodWithNoCode incorrectly retrieving class declarations

---

CHANGELOG.md
README.md
docs/ADDING_NEW_RULES.md
docs/CUSTOM_RULES.md
docs/MANUAL.md
docs/PROJECT_SCOPING.md
docs/delphi-custom-rules-example/README.md

Our README is (appropriately) terse when describing the process of using SonarDelphi, since it's primarily wrapped up in the Sonar ecosystem and should be explained well enough by their documentation. However, it can be quite an unstructured introduction to SonarDelphi on the whole, and our lack of guidance on how to configure Delphi projects could lead to prospective users incorrectly configuring their scans and being underwhelmed by the results.
This PR adds a friendly, descriptive guide to SonarQube and the Sonar ecosystem that covers:
- What SonarQube is
- How to split Delphi codebases into Sonar projects
- How to configure SonarDelphi scans
- How to configure rules for scans (quality profiles, template rules, custom rules, etc.)

Add SonarDelphi guide for new SonarQube users

---

CHANGELOG.md
delphi-frontend/src/main/java/au/com/integradev/delphi/operator/OperatorInvocableCollector.java
delphi-frontend/src/test/java/au/com/integradev/delphi/symbol/resolve/OperatorOverloadResolutionTest.java

By random chance, I noticed that `SubtractDataAggregator` wasn't actually being used in `OperatorOverloadResolutionTest`
This PR fixes the test and implements the correct type resolution for subtract expressions.

Fix type resolution inaccuracies around subtract expressions

---

CHANGELOG.md
delphi-checks-testkit/src/main/java/au/com/integradev/delphi/checks/verifier/CheckVerifierImpl.java
delphi-frontend/src/main/java/au/com/integradev/delphi/file/DelphiFile.java
delphi-frontend/src/main/java/au/com/integradev/delphi/utils/DelphiUtils.java
delphi-frontend/src/test/java/au/com/integradev/delphi/executor/DelphiSymbolTableExecutorTest.java

This PR fixes a bug that causes UNC paths to be mangled when converting the Sonar-provided file URI to an absolute path.
`java.io.File` and `java.nio.file.Path` are both convertible to a `java.net.URI`, but they treat UNC paths differently:
- `File` places the entire path in the path portion of the URI - `\\host\a\b\c` becomes `file:////host/a/b/c`
- `Path` (correctly) places the host in the host portion of the URI - `\\host\a\b\c` becomes `file://host/a/b/c`
We were mixing and matching our approach by feeding the `File` constructor with a URI constructed from a `Path` object. This PR fixes the issue by creating a `Path` from the URI, then creating the file via `Path.toFile` instead.

Handle UNC paths correctly during analysis

---

CHANGELOG.md
delphi-frontend/src/main/java/au/com/integradev/delphi/symbol/resolve/NameResolver.java

This PR fixes a `ClassCastException` that occurs when parsing fully qualified attribute references.
Fixes #213

Fix cast exception when parsing fully qualified attributes

---

CHANGELOG.md
delphi-frontend/src/main/antlr3/au/com/integradev/delphi/antlr/Delphi.g
delphi-frontend/src/main/java/org/sonar/plugins/communitydelphi/api/symbol/declaration/RoutineDirective.java
delphi-frontend/src/test/java/au/com/integradev/delphi/antlr/GrammarTest.java
delphi-frontend/src/test/resources/au/com/integradev/delphi/grammar/WinapiCallingConvention.pas

This PR fixes an accidental omission in the SonarDelphi grammar by adding support for the `winapi` calling convention.
Fixes #217

Add parsing support for `winapi` calling convention

---

delphi-checks-testkit/src/test/java/au/com/integradev/delphi/checks/verifier/CheckVerifierImplTest.java
delphi-checks/src/main/java/au/com/integradev/delphi/checks/AbstractGroupedDeclarationCheck.java
delphi-checks/src/main/java/au/com/integradev/delphi/checks/GroupedParameterDeclarationCheck.java

This PR adds a number of new test cases to CheckVerifier, improving test coverage around
- Messages in different situations
- Verifying parameters have been correctly set
- More quick fix cases
I've also fixed a Sonar issue in AbstractGroupedDeclaration.

Improve CheckVerifier testing

---

CHANGELOG.md
delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/ast/node/TryStatementNodeImpl.java
delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/ast/node/WhileStatementNodeImpl.java
delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/ast/visitors/SymbolTableVisitor.java
delphi-frontend/src/main/java/org/sonar/plugins/communitydelphi/api/ast/TryStatementNode.java
delphi-frontend/src/main/java/org/sonar/plugins/communitydelphi/api/ast/WhileStatementNode.java
delphi-frontend/src/test/java/au/com/integradev/delphi/executor/DelphiSymbolTableExecutorTest.java
delphi-frontend/src/test/resources/au/com/integradev/delphi/symbol/LocalScopes.pas

This PR improves the modeling of local scopes in the symbol table, which fixes #220.

Improve usage of local scopes in the symbol table

---

CHANGELOG.md
delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/ast/visitors/SymbolTableVisitor.java

This PR fixes a regression introduced by #223, which causes `if` guard expressions to be skipped over by the name resolver. 
This was manifesting in QA as large numbers of erroneous UnusedRoutine, UnusedLocalVariable, and VariableInitialization issues, and I have re-run a subset of the QA checks on this PR and found these issues are no longer cropping up.

Fix if guard expressions being incorrectly resolved

---

CHANGELOG.md
delphi-checks/src/main/java/au/com/integradev/delphi/utils/format/FormatStringParser.java
delphi-checks/src/test/java/au/com/integradev/delphi/checks/FormatArgumentTypeCheckTest.java
delphi-checks/src/test/java/au/com/integradev/delphi/checks/FormatStringValidCheckTest.java
delphi-checks/src/test/java/au/com/integradev/delphi/utils/format/FormatStringParserTest.java

This PR modifies the format string parser to match format specifiers case-insensitively, as specified in the Delphi documentation.
Fixes #228

Correctly handle uppercase format specifiers in format strings

---

CHANGELOG.md
delphi-checks/src/main/java/au/com/integradev/delphi/checks/GroupedParameterDeclarationCheck.java

This PR fixes a sequencing bug in the GroupedParameterDeclaration quick fix, in which text edits would be applied out of order.

Correct ordering of GroupedParameterDeclaration quick fix

---

CHANGELOG.md
delphi-checks-testkit/src/main/java/au/com/integradev/delphi/checks/verifier/Expectations.java
delphi-checks/src/main/java/au/com/integradev/delphi/checks/AbstractImportCheck.java
delphi-checks/src/main/java/au/com/integradev/delphi/checks/ImportSpecificityCheck.java
delphi-checks/src/main/java/au/com/integradev/delphi/checks/UnusedImportCheck.java
delphi-checks/src/test/java/au/com/integradev/delphi/checks/ImportSpecificityCheckTest.java
delphi-checks/src/test/java/au/com/integradev/delphi/checks/UnusedImportCheckTest.java
delphi-frontend/src/main/antlr3/au/com/integradev/delphi/antlr/Delphi.g
delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/ast/node/ImplementationSectionNodeImpl.java
delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/ast/node/InterfaceSectionNodeImpl.java
delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/ast/node/UsesClauseNodeImpl.java
delphi-frontend/src/main/java/org/sonar/plugins/communitydelphi/api/ast/ImplementationSectionNode.java
delphi-frontend/src/main/java/org/sonar/plugins/communitydelphi/api/ast/InterfaceSectionNode.java
delphi-frontend/src/main/java/org/sonar/plugins/communitydelphi/api/ast/UsesClauseNode.java

This PR adds the following quick fixes:
* "Move to implementation section" for `ImportSpecificity`
* "Remove unused import" for `UnusedImport`
This included adding a couple of new API methods:
* `ImplementationSectionNode::getUsesClause`
* `UsesClauseNode::getImports`

Add quick fixes for ImportSpecificity and UnusedImport

---

CHANGELOG.md
delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/ast/DelphiAstImpl.java
delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/ast/visitors/SonarSymbolTableVisitor.java
delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/ast/visitors/SymbolAssociationVisitor.java
delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/ast/visitors/SymbolTableVisitor.java
delphi-frontend/src/main/java/au/com/integradev/delphi/symbol/declaration/QualifiedNameDeclarationImpl.java
delphi-frontend/src/main/java/au/com/integradev/delphi/symbol/declaration/UnitNameDeclarationImpl.java
delphi-frontend/src/main/java/org/sonar/plugins/communitydelphi/api/ast/DelphiAst.java
delphi-frontend/src/test/java/au/com/integradev/delphi/executor/DelphiSymbolTableExecutorTest.java
delphi-frontend/src/test/java/au/com/integradev/delphi/symbol/declaration/UnitImportNameDeclarationTest.java
delphi-frontend/src/test/java/au/com/integradev/delphi/symbol/declaration/UnitNameDeclarationTest.java
delphi-frontend/src/test/resources/au/com/integradev/delphi/symbol/DefaultProgramName.dpr

This was partially implemented in #159, but stopped at the parsing level.
Throughout the analyzer, there were unsafe assumptions about the presence of a file header. The major area that needed extra consideration was symbol table construction.
It turns out that the default name of a Delphi program is `PROGRAM`, so this name ends up being used if the header is omitted. See `DefaultProgramName.dpr` for an example of a valid Delphi program that relies on this behavior.
Fixes #227

Improve support for program files omitting the `program` header

---

CHANGELOG.md
delphi-frontend/src/main/antlr3/au/com/integradev/delphi/antlr/Delphi.g
delphi-frontend/src/test/resources/au/com/integradev/delphi/grammar/AnonymousMethods.pas

This PR makes parsing more permissive around anonymous methods, treating them more like pure expressions.
Fixes #226

Promote anonymous methods to pure expressions in the grammar

---

CHANGELOG.md
sonar-delphi-plugin/src/main/java/au/com/integradev/delphi/DelphiRulesDefinition.java

This PR excludes checks annotated with `@SonarLintUnsupported` from being registered in the rule repository (i.e. in `DelphiRulesDefinition`. This fixes unsupported rules being defined and reported in a SonarLint context.

Exclude `@SonarLintUnsupported` rules in a SonarLint context

---

CHANGELOG.md
delphi-checks-testkit/src/main/java/au/com/integradev/delphi/builders/AbstractDelphiTestFile.java
delphi-checks-testkit/src/main/java/au/com/integradev/delphi/checks/verifier/DelphiCheckContextTester.java
delphi-checks/src/main/java/au/com/integradev/delphi/utils/IndentationUtils.java
delphi-frontend/src/main/java/au/com/integradev/delphi/check/DelphiCheckContextImpl.java
delphi-frontend/src/main/java/au/com/integradev/delphi/file/DefaultDelphiFile.java
delphi-frontend/src/main/java/au/com/integradev/delphi/file/DelphiFile.java
delphi-frontend/src/test/java/au/com/integradev/delphi/file/DelphiFileTest.java
delphi-frontend/src/test/resources/au/com/integradev/delphi/file/Utf8.pas

This PR fixes file pointer errors caused by an inconsistency in the 2 ways source files are read during `DelphiFile` construction.
* `DelphiFileStream` recognizes BOMs and strips them before passing the string data forward to the preprocessor
* `FileUtils.readLines` has no handling for BOMs and persists them into the string data
This inconsistency means that the length of the first line is incorrect according to `DelphiCheckContext::getFileLines`, and any rule relying on this API may accidentally report issues with positions that run over the end of the line. 
Fixes #234

Ensure BOM is not present in `DelphiCheckContext::getFileLines`

---

CHANGELOG.md
delphi-frontend/src/main/java/au/com/integradev/delphi/msbuild/DelphiProjectParser.java

This PR fixes scan failures that occur when a dproj file contains invalid (malformed) paths.
This change is difficult to test because most unix paths are well-formed.
Fixes #237

Fix scan failures on invalid paths in dproj files

---

CHANGELOG.md
delphi-checks/src/main/java/au/com/integradev/delphi/checks/PointerNameCheck.java
delphi-checks/src/main/resources/org/sonar/l10n/delphi/rules/community-delphi/PointerName.html
delphi-checks/src/test/java/au/com/integradev/delphi/checks/PointerNameCheckTest.java

This PR improves the behavior of the PointerName rule for types that do not follow naming conventions. It also allows pointers to types with the prefix E and I, in addition to the already supported T.
Fixes https://github.com/integrated-application-development/sonar-delphi/issues/238

Enhance PointerName rule analysis and documentation

---

CHANGELOG.md
delphi-frontend/src/main/antlr3/au/com/integradev/delphi/antlr/Delphi.g
delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/ast/node/LabelDeclarationNodeImpl.java
delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/ast/node/LabelStatementNodeImpl.java
delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/ast/node/NameDeclarationNodeImpl.java
delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/ast/node/SimpleNameDeclarationNodeImpl.java
delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/ast/visitors/DelphiParserVisitor.java
delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/ast/visitors/SymbolTableVisitor.java
delphi-frontend/src/main/java/au/com/integradev/delphi/symbol/declaration/LabelNameDeclarationImpl.java
delphi-frontend/src/main/java/au/com/integradev/delphi/symbol/scope/DelphiScopeImpl.java
delphi-frontend/src/main/java/org/sonar/plugins/communitydelphi/api/ast/GotoStatementNode.java
delphi-frontend/src/main/java/org/sonar/plugins/communitydelphi/api/ast/LabelDeclarationNode.java
delphi-frontend/src/main/java/org/sonar/plugins/communitydelphi/api/ast/LabelStatementNode.java
delphi-frontend/src/main/java/org/sonar/plugins/communitydelphi/api/symbol/declaration/LabelNameDeclaration.java
delphi-frontend/src/main/java/org/sonar/plugins/communitydelphi/api/symbol/scope/DelphiScope.java
delphi-frontend/src/test/java/au/com/integradev/delphi/executor/DelphiSymbolTableExecutorTest.java
delphi-frontend/src/test/java/au/com/integradev/delphi/symbol/scope/DelphiScopeImplTest.java
delphi-frontend/src/test/java/au/com/integradev/delphi/symbol/scope/UnknownScopeImplTest.java
delphi-frontend/src/test/resources/au/com/integradev/delphi/symbol/Labels.pas

This PR generally improves analysis of goto and labels:
- model `label` identifiers properly in the AST
- special handling for numeric label identifiers
- model `label` declarations properly in the AST
- new node type
- add labels to the symbol table
- new symbol declaration type
- ensure name resolution occurs for label references in `label` & `goto` statements
- expand the API around labels & goto in the AST and symbol APIs

Improve support for labels

---

CHANGELOG.md

This PR fixes a couple of minor issues in the changelog.
- Duplicate section in the 1.5.0 changelog
- Past-tense verb usage
It also adjusts the changelog from the recent `PointerName` improvements.

Tidy the changelog

---

CHANGELOG.md
delphi-frontend/src/main/antlr3/au/com/integradev/delphi/antlr/Delphi.g
delphi-frontend/src/test/resources/au/com/integradev/delphi/grammar/KeyWordsAsIdentifier.pas

This apparently used to be allowed in Delphi.NET.

Allow `Label` keyword as an identifier

---

delphi-checks/src/main/resources/org/sonar/l10n/delphi/rules/community-delphi/PointerName.html

This PR adds the word "the" to the `PointerName` description. 🎉
(I also reflowed the line wrapping a bit.)

Fix typo in `PointerName` description

---

README.md

Good news!
It turns out that current versions of Delphi CE actually do include the standard library source code.

Remove warning about Delphi Community Edition being unsupported

---

CHANGELOG.md
delphi-checks/src/main/java/au/com/integradev/delphi/checks/CheckList.java
delphi-checks/src/main/java/au/com/integradev/delphi/checks/InheritedMethodWithNoCodeCheck.java
delphi-checks/src/main/java/au/com/integradev/delphi/checks/RedundantInheritedCheck.java
delphi-checks/src/main/java/au/com/integradev/delphi/utils/RoutineUtils.java
delphi-checks/src/main/resources/org/sonar/l10n/delphi/rules/community-delphi/RedundantInherited.html
delphi-checks/src/main/resources/org/sonar/l10n/delphi/rules/community-delphi/RedundantInherited.json
delphi-checks/src/main/resources/org/sonar/l10n/delphi/rules/community-delphi/Sonar_way_profile.json
delphi-checks/src/test/java/au/com/integradev/delphi/checks/RedundantInheritedCheckTest.java

A bare `inherited` statement can be put in any method, regardless of whether the method is overriding a parent's.
The compiler treats these as no-ops, which indicates they can be removed. Using these statements without overriding a method makes the code far more confusing.

Add check for redundant inherited statements

---

CHANGELOG.md
delphi-checks/src/main/java/au/com/integradev/delphi/checks/ShortIdentifierCheck.java

This PR updates the default exclusion list for `ShortIdentifier` to add some common loop counter names (we already had `I`):
* `II`
* `III`
* `J`
* `K`

Add extra exclusions for common loop counter names in `ShortIdentifier`

---

delphi-checks/src/main/java/au/com/integradev/delphi/checks/RedundantInheritedCheck.java

This change:
- Removes unnecessary parentheses
- Replaces a lambda with a method reference
- Changed the type of an `int` expression to `long`

Fix sonar issues in `RedundantInheritedCheck`

---

CHANGELOG.md
delphi-checks/src/main/java/au/com/integradev/delphi/checks/LowercaseKeywordCheck.java

A small improvement to the `LowercaseKeywordCheck` rule, now the issue message shows the current value and the expected value, making it easier for users to understand what needs to be fixed.
In addition to making the problem even more intuitive, this change makes it possible to know what the problem is directly from the issues list.

Add found and expected value to `LowercaseKeywordCheck` message

---

CHANGELOG.md
delphi-frontend/src/main/java/au/com/integradev/delphi/nunit/NUnit2FileParser.java
delphi-frontend/src/main/java/au/com/integradev/delphi/nunit/NUnit3FileParser.java
delphi-frontend/src/test/java/au/com/integradev/delphi/nunit/DelphiNUnitParserTest.java
delphi-frontend/src/test/resources/au/com/integradev/delphi/nunit/reports/v2/unusualStatusCasing/results.xml
delphi-frontend/src/test/resources/au/com/integradev/delphi/nunit/reports/v3/unusualStatusCasing/results.xml

This PR fixes a bug where the `result` attribute was treated as a case-sensitive string in NUnit test reports, causing unusual casings to be erroneously reported as `TestResult.Status.FAILURE`.

Treat `result` attribute as case-insensitive in NUnit test reports

---

CHANGELOG.md
delphi-checks/src/main/java/au/com/integradev/delphi/checks/UnusedPropertyCheck.java
delphi-checks/src/test/java/au/com/integradev/delphi/checks/UnusedPropertyCheckTest.java
delphi-frontend/src/main/antlr3/au/com/integradev/delphi/antlr/Delphi.g
delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/ast/node/PropertyDefaultSpecifierNodeImpl.java
delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/ast/node/PropertyImplementsSpecifierNodeImpl.java
delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/ast/node/PropertyIndexSpecifierNodeImpl.java
delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/ast/node/PropertyNodeImpl.java
delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/ast/node/PropertyStoredSpecifierNodeImpl.java
delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/ast/node/StringTypeNodeImpl.java
delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/ast/visitors/DelphiParserVisitor.java
delphi-frontend/src/main/java/au/com/integradev/delphi/symbol/declaration/PropertyNameDeclarationImpl.java
delphi-frontend/src/main/java/au/com/integradev/delphi/symbol/resolve/NameResolutionHelper.java
delphi-frontend/src/main/java/org/sonar/plugins/communitydelphi/api/ast/PropertyDefaultSpecifierNode.java
delphi-frontend/src/main/java/org/sonar/plugins/communitydelphi/api/ast/PropertyImplementsSpecifierNode.java
delphi-frontend/src/main/java/org/sonar/plugins/communitydelphi/api/ast/PropertyIndexSpecifierNode.java
delphi-frontend/src/main/java/org/sonar/plugins/communitydelphi/api/ast/PropertyNode.java
delphi-frontend/src/main/java/org/sonar/plugins/communitydelphi/api/ast/PropertyStoredSpecifierNode.java
delphi-frontend/src/test/java/au/com/integradev/delphi/executor/DelphiSymbolTableExecutorTest.java
delphi-frontend/src/test/resources/au/com/integradev/delphi/symbol/properties/DefaultProperties.pas
delphi-frontend/src/test/resources/au/com/integradev/delphi/symbol/properties/ImplementsProperties.pas
delphi-frontend/src/test/resources/au/com/integradev/delphi/symbol/properties/IndexProperties.pas
delphi-frontend/src/test/resources/au/com/integradev/delphi/symbol/properties/StoredProperties.pas

The original goal of this PR was just to exclude properties with an `implements` specifier in the `UnusedProperty` rule.
It ended up doing a bit more than that:
* Modeled all of the non-trivial property specifiers as proper AST nodes (`default`, `implements`, `index`, `stored`)
* Fixed a bug where name resolution did not occur for type references in `implements` specifiers
* Excluded properties with an `implements` specifier in `UnusedProperty` (easiest part...)
* Fixed overly-permissive parsing rules where `string` and `file` were erroneously permitted **anywhere** that `typeReference` was allowed.

Improve analysis and modeling around property specifiers

---

CHANGELOG.md
delphi-frontend/src/main/java/au/com/integradev/delphi/msbuild/DelphiProjectParser.java
delphi-frontend/src/test/java/au/com/integradev/delphi/msbuild/DelphiProjectParserTest.java
delphi-frontend/src/test/resources/au/com/integradev/delphi/msbuild/LibraryPath.dproj

This PR adds support for the global library path.
All we had to do was grab the `DelphiLibraryPath` and `DelphiTranslatedLibraryPath` properties and append them to the `DCC_UnitSearchPath` to complete the search path.
These properties are reflected from the registry to `EnvOptions.proj` by the IDE, which is how they become available to MSBuild and by extension the analyzer.
The nice thing is that 95% of the work for this was done a long time ago when we implemented comprehensive support for MSBuild project files.
Closes #254.

Add support for the library path

---

CHANGELOG.md
delphi-checks/src/main/java/au/com/integradev/delphi/checks/LowercaseKeywordCheck.java
delphi-checks/src/test/java/au/com/integradev/delphi/checks/LowercaseKeywordCheckTest.java

This PR add "Correct to %s" quick fix for `LowercaseKeywordCheck` rule, in a similar way to what already exists for the `MixedNamesCheck` rule.

Add quick fixes for `LowercaseKeywordCheck`

---

delphi-checks-testkit/src/main/java/au/com/integradev/delphi/checks/verifier/CheckVerifierImpl.java

This PR fixes a bug in the CheckVerifier implementation that causes tests to fail when the number of Sonar-level text replacements does not match the number of SonarDelphi-level quick fix edits. Because one `QuickFixEdit` can correspond to multiple text replacements (e.g. `QuickFixEdit.move`, which replaces two ranges), this test could cause valid quick fixes to fail.
We don't currently have any quick fixes that encounter this problem in tests.

Fix bug in CheckVerifier quick fix text edit assertions

---

CHANGELOG.md
delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/ast/node/ArrayConstructorNodeImpl.java

Previously, the `ArrayConstructorNode` image for `['a'..'z']` looked like `[[, 'a'..'z']`. This PR corrects that behaviour.

Fix ArrayConstructorNode image

---

delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/ast/node/ArrayConstructorNodeImpl.java

This fixes https://sonarcloud.io/project/issues?open=AZEF3qlXn5xwAMRtHSB5&id=integrated-application-development_sonar-delphi

Cast operand of subtraction to `long` in `ArrayConstructorNodeImpl`

---

CHANGELOG.md

This PR updates the changelog to reflect that the changes in #272 also improve `InheritedMethodWithNoCode`.

Reference `InheritedMethodWithNoCode` in changelog entry

---

delphi-frontend/src/main/java/au/com/integradev/delphi/msbuild/DelphiProjectParser.java

In #267, we added support for the library path by manually adding `DelphiLibraryPath` and `DelphiTranslatedLibraryPath` to the search path in `DelphiProjectParser`.
This works well, but produces some noisy warnings when paths in the library path properties don't exist.
By default, the library path contains non-existent paths.
We're already special-casing the construction of the search path here, so what's one more kludge?
This PR silences warnings when constructing path lists for the `DelphiLibraryPath` and `DelphiTranslatedLibraryPath` properties.

Silence noisy warnings around library path properties

---

CHANGELOG.md
delphi-frontend/src/main/antlr3/au/com/integradev/delphi/antlr/Delphi.g
delphi-frontend/src/test/java/au/com/integradev/delphi/antlr/GrammarTest.java
delphi-frontend/src/test/resources/au/com/integradev/delphi/grammar/ConditionalAsm.pas

This PR implements a hack that exits `asmMode` when we see the `begin` keyword.
We're opting for this hack so that we can support cases where an `asm` block shares an `end` with some other block due to conditional compilation.
For example, see:
https://github.com/pleriche/FastMM5/blob/b2fc04fad7628e24901386322dbcfb0d2cbbcddf/FastMM5.pas#L5649
Fixes #269.

Improve parsing around partial `asm` blocks in conditional branches

---

CHANGELOG.md
delphi-checks/src/main/java/au/com/integradev/delphi/checks/VariableInitializationCheck.java
delphi-checks/src/test/java/au/com/integradev/delphi/checks/VariableInitializationCheckTest.java

This PR changes the `VariableInitialization` rule to treat `out` parameters as uninitialized at the start of a routine.
Closes #134.

Treat `out` parameters as uninitialized in `VariableInitialization`

---

CHANGELOG.md
delphi-checks/src/main/java/au/com/integradev/delphi/checks/CaseStatementSizeCheck.java
delphi-checks/src/test/java/au/com/integradev/delphi/checks/CaseStatementSizeCheckTest.java
delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/ast/node/CaseItemStatementNodeImpl.java
delphi-frontend/src/main/java/org/sonar/plugins/communitydelphi/api/ast/CaseItemStatementNode.java

This PR improves the `CaseStatementSize` rule, counting `case` items with multiple values as if they were flattened out to multiple case items.
For example, the following `case` statement will no longer raise an issue:
```pas
case Foo of
123, 456: Bar;
end;
```

Fix FPs on case items with multiple values in `CaseStatementSize`

---

CHANGELOG.md
delphi-frontend/src/main/java/au/com/integradev/delphi/symbol/resolve/TypeInferrer.java
delphi-frontend/src/test/java/au/com/integradev/delphi/symbol/resolve/TypeInferrerTest.java

This PR generally improves type inference around:
- unsigned integer literals
- array constructor expressions containing integer literals
- real expressions (closes #123)
Additionally, I've added a `TypeInferrerTest` suite to test the `TypeInferrer` more directly, as opposed to the more limited/indirect testing we're currently getting through the `SymbolTableExecutor` tests.

Improve type inference

---

CHANGELOG.md
delphi-frontend/src/main/java/au/com/integradev/delphi/type/factory/StructTypeImpl.java

`StructTypeImpl.parent` was not being resolved correctly when the relevant ancestor was a type alias.
This was because we did an `instanceof StructTypeImpl` check, which is incompatible with the generated type alias impl classes introduced in b3b14dd58f27e1b5b5f5b65dfb53f37aced1b012.
Fixes #288.

Fix name resolution errors around alias ancestor types

---

CHANGELOG.md
delphi-checks/src/main/java/au/com/integradev/delphi/checks/RedundantParenthesesCheck.java
delphi-checks/src/main/resources/org/sonar/l10n/delphi/rules/community-delphi/RedundantParentheses.html
delphi-checks/src/test/java/au/com/integradev/delphi/checks/RedundantParenthesesCheckTest.java

This PR slightly expands the `RedundantParentheses` rule to target parenthesized primary expressions.
Much like doubled-up pairs of parentheses, a parenthesized primary expression is never meaningful syntactically, or more readable for a human.

Target parenthesized primary expressions in `RedundantParentheses`

---

CHANGELOG.md
delphi-checks/src/main/java/au/com/integradev/delphi/checks/RedundantParenthesesCheck.java
delphi-checks/src/test/java/au/com/integradev/delphi/checks/RedundantParenthesesCheckTest.java

This PR changes the `RedundantParentheses` rule to exclude non-trivial `inherited` expressions.
Parenthesized bare `inherited` is still flagged, but anything more complex is now ignored.

Exclude non-trivial `inherited` expressions in `RedundantParentheses`

---

CHANGELOG.md
delphi-checks/src/test/java/au/com/integradev/delphi/checks/RedundantParenthesesCheckTest.java
delphi-frontend/src/main/antlr3/au/com/integradev/delphi/antlr/Delphi.g

This PR fixes a parsing bug where const array literal expressions would be confused with parenthesized primary expressions.
The official parser builds type information incrementally during parsing and relies on it to know what may appear on the right side of an assignment (which is another point in favor of #261).
With our current approach to parsing, the fix for this problem is a slightly gnarly repetition of rules in the ANTLR3 grammar.

Disambiguate const array literals from parenthesized primary expressions

---

delphi-frontend/pom.xml
delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/DelphiFileStream.java
delphi-frontend/src/test/java/au/com/integradev/delphi/msbuild/condition/VersionTest.java
delphi-frontend/src/test/java/au/com/integradev/delphi/operator/OperatorIntrinsicTest.java
delphi-frontend/src/test/java/au/com/integradev/delphi/symbol/declaration/EnumElementNameDeclarationTest.java
delphi-frontend/src/test/java/au/com/integradev/delphi/symbol/declaration/RoutineNameDeclarationTest.java
delphi-frontend/src/test/java/au/com/integradev/delphi/symbol/declaration/TypeParameterNameDeclarationTest.java
delphi-frontend/src/test/java/au/com/integradev/delphi/symbol/declaration/UnitImportNameDeclarationTest.java
delphi-frontend/src/test/java/au/com/integradev/delphi/symbol/declaration/UnitNameDeclarationTest.java
delphi-frontend/src/test/java/au/com/integradev/delphi/symbol/occurrence/NameOccurrenceImplTest.java
delphi-frontend/src/test/java/au/com/integradev/delphi/type/generic/TypeSpecializationContextTest.java
delphi-frontend/src/test/java/au/com/integradev/delphi/type/parameter/ParameterTest.java
delphi-tokens-generator-maven-plugin/pom.xml
docs/delphi-custom-rules-example/pom.xml
license-maven-plugin/pom.xml
pom.xml

This PR upgrades various dependencies and fixes resulting warnings from javac and errorprone.

Upgrade dependencies

---

CHANGELOG.md
delphi-checks/src/main/java/au/com/integradev/delphi/checks/CheckList.java
delphi-checks/src/main/java/au/com/integradev/delphi/checks/FullyQualifiedImportCheck.java
delphi-checks/src/main/resources/org/sonar/l10n/delphi/rules/community-delphi/FullyQualifiedImport.html
delphi-checks/src/main/resources/org/sonar/l10n/delphi/rules/community-delphi/FullyQualifiedImport.json
delphi-checks/src/test/java/au/com/integradev/delphi/checks/FullyQualifiedImportCheckTest.java

This PR implements a new rule: FullyQualifiedImportCheck.
As sugested in https://github.com/integrated-application-development/sonar-delphi/issues/62, this rule simply checks if the imports in the UsesClausesNode are fully qualified. If they are not, an issue is raised, suggesting to change it to be fully qualified.

Create rule FullyQualifiedImportCheck

---

CHANGELOG.md
delphi-checks/src/main/java/au/com/integradev/delphi/checks/FullyQualifiedImportCheck.java
delphi-checks/src/test/java/au/com/integradev/delphi/checks/FullyQualifiedImportCheckTest.java
delphi-frontend/src/main/java/au/com/integradev/delphi/symbol/SymbolTableBuilder.java
delphi-frontend/src/main/java/au/com/integradev/delphi/symbol/declaration/UnitImportNameDeclarationImpl.java
delphi-frontend/src/main/java/org/sonar/plugins/communitydelphi/api/symbol/declaration/UnitImportNameDeclaration.java
delphi-frontend/src/test/java/au/com/integradev/delphi/symbol/declaration/UnitImportNameDeclarationTest.java

This PR fixes an issue in `FullyQualifiedImport` where unit aliases weren't considered, causing false positives on aliased imports.

Handle aliased imports in `FullyQualifiedImport`

---

delphi-checks/src/test/java/au/com/integradev/delphi/checks/BeginEndRequiredCheckTest.java
delphi-checks/src/test/java/au/com/integradev/delphi/checks/CheckTestNameTest.java
delphi-checks/src/test/java/au/com/integradev/delphi/checks/ClassPerFileCheckTest.java
delphi-checks/src/test/java/au/com/integradev/delphi/checks/CognitiveComplexityRoutineCheckTest.java
delphi-checks/src/test/java/au/com/integradev/delphi/checks/CommentedOutCodeCheckTest.java
delphi-checks/src/test/java/au/com/integradev/delphi/checks/ConstructorNameCheckTest.java
delphi-checks/src/test/java/au/com/integradev/delphi/checks/CyclomaticComplexityRoutineCheckTest.java
delphi-checks/src/test/java/au/com/integradev/delphi/checks/EmptyFileCheckTest.java
delphi-checks/src/test/java/au/com/integradev/delphi/checks/EmptyRoutineCheckTest.java
delphi-checks/src/test/java/au/com/integradev/delphi/checks/FieldNameCheckTest.java
delphi-checks/src/test/java/au/com/integradev/delphi/checks/GroupedParameterDeclarationCheckTest.java
delphi-checks/src/test/java/au/com/integradev/delphi/checks/HelperNameCheckTest.java
delphi-checks/src/test/java/au/com/integradev/delphi/checks/ImplicitDefaultEncodingCheckTest.java
delphi-checks/src/test/java/au/com/integradev/delphi/checks/LowercaseKeywordCheckTest.java
delphi-checks/src/test/java/au/com/integradev/delphi/checks/MissingSemicolonCheckTest.java
delphi-checks/src/test/java/au/com/integradev/delphi/checks/MixedNamesCheckTest.java
delphi-checks/src/test/java/au/com/integradev/delphi/checks/RedundantInheritedCheckTest.java
delphi-checks/src/test/java/au/com/integradev/delphi/checks/RoutineNameCheckTest.java
delphi-checks/src/test/java/au/com/integradev/delphi/checks/TabulationCharacterCheckTest.java
delphi-checks/src/test/java/au/com/integradev/delphi/checks/TypeAliasCheckTest.java
delphi-checks/src/test/java/au/com/integradev/delphi/checks/VariableInitializationCheckTest.java
delphi-checks/src/test/java/au/com/integradev/delphi/checks/VariableNameCheckTest.java
delphi-checks/src/test/java/au/com/integradev/delphi/checks/VisibilityKeywordIndentationCheckTest.java
delphi-checks/src/test/java/au/com/integradev/delphi/checks/VisibilitySectionOrderCheckTest.java

It is common for a test name not to represent what it is asserting. An example of this is a test named `...ShouldAddIssue` calling `verifyNoIssues`.
This PR adds some architecture tests targeting checks that assert:
* Test names are accurate to the assertion
* All checks have test units
* All test units have an associated check

Add architecture tests for test classes and methods

---

CHANGELOG.md
delphi-frontend/src/main/antlr3/au/com/integradev/delphi/antlr/Delphi.g
delphi-frontend/src/test/java/au/com/integradev/delphi/file/DelphiFileTest.java
delphi-frontend/src/test/resources/au/com/integradev/delphi/file/SkipImplementation.pas
delphi-frontend/src/test/resources/au/com/integradev/delphi/file/SkipImplementationWithDirectiveNesting.pas

In 50726816e318afb456ad0d04fcb2acb22cdf1478, we implemented keyword case-insensitivity directly into the grammar. This gave us a small performance boost, but quietly impaired our ability to track `directiveNesting` while lexing a source file.
We were using the case-sensitive `String#startsWith` to check for a particular compiler directive while lexing the token, which used to work because the input actually was lowercase before. Now, we need to do a case-insensitive comparison because the input is using the original casing.
This `directiveNesting` issue introduced some subtle issues in cases where:
- we're only parsing the interface of a file (skipping the `implementation` section
- `implementation` keywords are nested within conditional directives (`$IF(DEF)`, `$SLSE`)
- the conditional …

Fix parsing errors on `implementation` keywords in conditional branches

---

CHANGELOG.md
delphi-checks/src/test/java/au/com/integradev/delphi/checks/VariableInitializationCheckTest.java
delphi-frontend/src/main/antlr3/au/com/integradev/delphi/antlr/Delphi.g
delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/ast/node/AnonymousMethodHeadingNodeImpl.java
delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/ast/node/AnonymousMethodNodeImpl.java
delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/ast/node/ProceduralTypeNodeImpl.java
delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/ast/node/ProcedureOfObjectTypeNodeImpl.java
delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/ast/node/ProcedureReferenceTypeNodeImpl.java
delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/ast/node/ProcedureTypeHeadingNodeImpl.java
delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/ast/node/ProcedureTypeNodeImpl.java
delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/ast/visitors/DelphiParserVisitor.java
delphi-frontend/src/main/java/au/com/integradev/delphi/symbol/declaration/RoutineNameDeclarationImpl.java
delphi-frontend/src/main/java/au/com/integradev/delphi/type/factory/ProceduralTypeImpl.java
delphi-frontend/src/main/java/au/com/integradev/delphi/type/factory/TypeFactoryImpl.java
delphi-frontend/src/main/java/org/sonar/plugins/communitydelphi/api/ast/AnonymousMethodHeadingNode.java
delphi-frontend/src/main/java/org/sonar/plugins/communitydelphi/api/ast/ProceduralTypeNode.java
delphi-frontend/src/main/java/org/sonar/plugins/communitydelphi/api/ast/ProcedureTypeHeadingNode.java
delphi-frontend/src/main/java/org/sonar/plugins/communitydelphi/api/type/Type.java
delphi-frontend/src/test/java/au/com/integradev/delphi/symbol/declaration/RoutineNameDeclarationTest.java
delphi-frontend/src/test/java/au/com/integradev/delphi/symbol/resolve/TypeComparerTest.java
delphi-frontend/src/test/java/au/com/integradev/delphi/symbol/resolve/TypeInferrerTest.java
delphi-frontend/src/test/java/au/com/integradev/delphi/type/factory/TypeAliasGeneratorTest.java
delphi-frontend/src/test/resources/au/com/integradev/delphi/grammar/AnonymousMethods.pas

This PR makes a few improvements:
* fixes parsing errors on anonymous methods with routine directives
* fixes an issue where non-routine procedural types (procvars, anonymous methods, etc.) could never be considered variadic
* which fixes a downstream `IndexOutOfBoundsException` that surfaced in the `VariableInitialization` rule 
* tidies the AST a bit around anonymous methods by introducing `AnonymousMethodHeadingNode`
* persists routine directives into `ProcedureType`
Fixes #172 and #297.

Improve procedural type modeling around routine directives

---

CHANGELOG.md
delphi-checks/src/main/java/au/com/integradev/delphi/checks/CheckList.java
delphi-checks/src/main/java/au/com/integradev/delphi/checks/MissingRaiseCheck.java
delphi-checks/src/main/resources/org/sonar/l10n/delphi/rules/community-delphi/MissingRaise.html
delphi-checks/src/main/resources/org/sonar/l10n/delphi/rules/community-delphi/MissingRaise.json
delphi-checks/src/main/resources/org/sonar/l10n/delphi/rules/community-delphi/Sonar_way_profile.json
delphi-checks/src/test/java/au/com/integradev/delphi/checks/MissingRaiseCheckTest.java

This PR adds a rule to detect when an exception has been created, but not raised, e.g.
```delphi
Exception.Create('Error!');
```
instead of
```delphi
raise Exception.Create('Error!');
```
In a separate commit, I've also fixed a typo I noticed in the changelog.

Add check for discarded exceptions

---

delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/ast/node/AnonymousMethodHeadingNodeImpl.java
delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/ast/node/RoutineHeadingNodeImpl.java
delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/ast/node/utils/RoutineDirectiveUtils.java

There's a bit of shared (copy-pasted) code between `AnonymousMethodHeadingNodeImpl` and `RoutineHeadingNodeImpl` around constructing a set of routine directives based on child nodes.
This PR pulls that shared code out into a small util.

Reduce duplication around `getDirectives` methods

---

delphi-checks/src/main/java/au/com/integradev/delphi/checks/MissingRaiseCheck.java
delphi-checks/src/test/java/au/com/integradev/delphi/checks/MissingRaiseCheckTest.java

This PR fixes an issue with the new MissingRaise rule that would cause it to raise false positives on constructor calls on `Self`, when `Self` is an exception type. For example:
```delphi
type
EMyError = class(Exception)
public
constructor Create(S: string);
constructor Create(A: Integer; B: Integer);
end;
constructor EMyError.Create(A: Integer; B: Integer);
begin
// ...
Create('Default message'); // <- Raises a false positive issue
// ...
end;
```

Fix MissingRaise false positives on Self constructor calls

---

CHANGELOG.md
delphi-frontend/src/main/java/au/com/integradev/delphi/type/factory/TypeFactoryImpl.java
delphi-frontend/src/main/java/au/com/integradev/delphi/type/intrinsic/IntrinsicReturnType.java
delphi-frontend/src/test/java/au/com/integradev/delphi/type/intrinsic/IntrinsicReturnTypeTest.java

This PR makes the return types for the `Length`, `High`, and `Low` intrinsics more accurate.
The new rules are:
* all array types are always size `Integer` on 32-bit on all compiler versions
* dynamic array types are size `NativeInt` on 64-bit on all compiler versions
* open array types are size `Integer` on 64-bit on all compiler versions prior to 36.0
* open array types are size `NativeInt` on 64-bit on all compiler versions from 36.0
Fixes #296.

Fix return types for `Length`/ `High`/ `Low` on open/dynamic arrays

---

pom.xml

This removes vulnerable protobuf-java and okio-jvm versions from our dependency tree.

Bump `sonar-ws` and `sonar-plugin-api-impl` to 10.7.0.96327

---

CHANGELOG.md
delphi-frontend/src/main/antlr3/au/com/integradev/delphi/antlr/Delphi.g
delphi-frontend/src/test/java/au/com/integradev/delphi/antlr/GrammarTest.java
delphi-frontend/src/test/resources/au/com/integradev/delphi/grammar/SemicolonSeparatedGenericArguments.pas

Previously, only comma-delimited type parameters were parsing correctly.
Fixes #302.

Fix parsing errors on semicolon-delimited generic type parameters in routine implementation headers

---

CHANGELOG.md
delphi-checks-testkit/src/main/java/au/com/integradev/delphi/checks/verifier/DelphiCheckContextTester.java
delphi-frontend/src/main/java/au/com/integradev/delphi/check/DelphiCheckContextImpl.java
delphi-frontend/src/main/java/org/sonar/plugins/communitydelphi/api/check/DelphiCheckContext.java

This PR adds a new `DelphiCheckContext::getUri` method to expose the URI of the file under analysis.

Expose URI of the analyzed file through `DelphiCheckContext::getUri`

---

CHANGELOG.md
delphi-frontend/src/main/java/au/com/integradev/delphi/type/factory/TypeFactoryImpl.java
delphi-frontend/src/main/java/au/com/integradev/delphi/type/intrinsic/IntrinsicArgumentMatcher.java
delphi-frontend/src/main/java/au/com/integradev/delphi/type/intrinsic/IntrinsicReturnType.java
delphi-frontend/src/main/java/au/com/integradev/delphi/type/intrinsic/IntrinsicsInjector.java
delphi-frontend/src/test/java/au/com/integradev/delphi/type/intrinsic/IntrinsicArgumentMatcherTest.java

This PR fixes several intrinsic signatures to handle array size types properly.
It's a symmetrical change with #312.
Due to the current asymmetry, it's very trivial to get `PlatformDependentTruncation` false-positives with cases like:
```pas
procedure Test(Foo: TArray<Byte>; Bar: TArray<Byte>);
begin
// Length returns NativeInt, and SetLength incorrectly expects Integer.
SetLength(Foo, Length(Bar));
end;
```

Fix various intrinsic signatures around dynamic and open arrays

---

CHANGELOG.md
delphi-checks/src/main/java/au/com/integradev/delphi/checks/PlatformDependentTruncationCheck.java
delphi-checks/src/test/java/au/com/integradev/delphi/checks/PlatformDependentTruncationCheckTest.java

Under 64-bit toolchains, `PlatformDependentTruncation` currently produces false positives around binary expressions with platform-dependent operands.
```pas
procedure Test(Nat: NativeInt);
begin
Nat := Nat + 1;
end;
```
* On a 64-bit toolchain, the expression `Nat + 1` has result type `Int64` because the `Int64` overload of the `Add` operator intrinsic is selected.
* On a 64-bit toolchain, the assignment expression is `<NativeInt> = <Int64>`, and so the rule says "hey, `Int64` doesn't fit into `NativeInt` on 32-bit, that will truncate!"
* What the rule doesn't understand is that, on a 32-bit toolchain, a different overload of the `Add` operator intrinsic will be selected and the result type will be `Integer` - giving us an effective expression of `<32-bit NativeInt> = <Integer>` on that …

Fix FPs around binary expressions in `PlatformDependentTruncation`

---

CHANGELOG.md
delphi-frontend/src/main/java/au/com/integradev/delphi/symbol/resolve/NameResolver.java
delphi-frontend/src/test/java/au/com/integradev/delphi/executor/DelphiSymbolTableExecutorTest.java
delphi-frontend/src/test/resources/au/com/integradev/delphi/symbol/properties/ArrayProperties.pas
delphi-frontend/src/test/resources/au/com/integradev/delphi/symbol/properties/ClassArrayProperties.pas

#313 introduced a regression in type resolution for plain array properties.
We started erroneously calling `addResolvedDeclaration()` before resolving array properties, where before we would exit immediately and return to argument disambiguation on the array accessor.
The effect was a subtle breakage of the type resolution around array properties. Take, for example, the expression `Foo.Bar[0]`, where `Bar` is an array property returning `string`. The old behavior would yield type `string`, while the new behavior would yield type `Char` due to the premature `addResolvedDeclaration()` call updating the `currentType` to `string` before the array accessor was processed.

Fix incorrect type resolution around array property accesses

---

.github/workflows/scan-dependencies.yml

@spiltcoffee, a replacement for the automatic dependency submission.
The automatic dependency submission always fails on release commits because the new versions for `delphi-tokens-generator-maven-plugin` and `license-maven-plugin` are unavailable until they've been published.
This new workflow installs everything locally before running the dependency submission.

Implement Dependency Submission workflow

---

CHANGELOG.md
delphi-frontend/src/main/java/au/com/integradev/delphi/coverage/DelphiCodeCoverageParser.java
delphi-frontend/src/main/java/au/com/integradev/delphi/msbuild/DelphiProjectHelper.java
delphi-frontend/src/test/java/au/com/integradev/delphi/coverage/delphicodecoveragetool/DelphiCoverageToolParserTest.java
delphi-frontend/src/test/resources/au/com/integradev/delphi/projects/SimpleProject/delphicodecoveragereports/MismatchedCasingCoverage.xml

File names in coverage reports are now treated as case-insensitive on windows.
Fixes #325.

Fix case-sensitive treatment of file names in coverage reports

---

CHANGELOG.md
delphi-frontend/src/main/java/au/com/integradev/delphi/msbuild/DelphiProject.java
delphi-frontend/src/main/java/au/com/integradev/delphi/msbuild/DelphiProjectHelper.java
delphi-frontend/src/main/java/au/com/integradev/delphi/msbuild/DelphiProjectParser.java
delphi-frontend/src/main/java/au/com/integradev/delphi/symbol/SymbolTableBuilder.java
delphi-frontend/src/test/java/au/com/integradev/delphi/msbuild/DelphiProjectParserTest.java
delphi-frontend/src/test/java/au/com/integradev/delphi/symbol/SymbolTableBuilderTest.java
delphi-frontend/src/test/resources/au/com/integradev/delphi/msbuild/BrowsingPath.dproj
sonar-delphi-plugin/src/main/java/au/com/integradev/delphi/DelphiSensor.java

This PR includes the browsing path in the search path, makes changes to the order of paths during `SearchPath` creation, and changes up the order of the unit data processing in the `SymbolTableBuilder`.
The new search path priority is (highest to lowest):
- `sonar.sources`
- `DCCReference`
- `DCC_UnitSearchPath`
- `Debugger_DebugSourcePath`
- `DelphiLibraryPath`
- `DelphiTranslatedLibraryPath`
- `DelphiBrowsingPath`
- Standard library
This change enables behaviors like:
- shadowing standard library units with a unit on `DCC_UnitSearchPath`
- shadowing `DCC_UnitSearchPath` units with a `DCCReference` unit
These cases are somewhat unusual, but they are possible in Delphi.

Reprioritize the analysis search path

---

CHANGELOG.md
delphi-checks/src/main/java/au/com/integradev/delphi/checks/EmptyBlockCheck.java
delphi-checks/src/main/java/au/com/integradev/delphi/checks/EmptyRoutineCheck.java
delphi-checks/src/main/resources/org/sonar/l10n/delphi/rules/community-delphi/EmptyRoutine.html
delphi-checks/src/test/java/au/com/integradev/delphi/checks/EmptyBlockCheckTest.java
delphi-checks/src/test/java/au/com/integradev/delphi/checks/EmptyRoutineCheckTest.java
delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/ast/node/AnonymousMethodNodeImpl.java
delphi-frontend/src/main/java/org/sonar/plugins/communitydelphi/api/ast/AnonymousMethodNode.java

This PR excludes anonymous methods from `EmptyBlock` and flags them in `EmptyRoutine` instead.
Fixes #315.

Handle empty anonymous methods in `EmptyRoutine` instead of `EmptyBlock`

---

CHANGELOG.md

While reviewing the changelog, I noticed some entries were in the wrong section.

Move API additions to `Added` section of changelog

---

CHANGELOG.md
delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/ast/node/AnonymousMethodNodeImpl.java
delphi-frontend/src/main/java/org/sonar/plugins/communitydelphi/api/ast/AnonymousMethodNode.java

This PR fixes a bug in the `getStatementBlock` implementation, and adds a `getDeclarationSection` method.

Tidy the `AnonymousMethodNode` API

---

CHANGELOG.md
delphi-frontend/src/main/java/au/com/integradev/delphi/symbol/SymbolTableBuilder.java
delphi-frontend/src/test/java/au/com/integradev/delphi/symbol/SymbolTableBuilderTest.java

The previous approach (where `sonar.sources` took first priority in the analysis search path) caused some surprising/undesirable behavior in projects where there are multiple units with the same name.
It becomes very hard in that scenario for a user to configure the scan in a way where the correct unit will win during import resolution, even if the search path was correct in the dproj file.

Deprioritize `sonar.sources` in the analysis search path

---

CHANGELOG.md
delphi-frontend/src/main/antlr3/au/com/integradev/delphi/antlr/Delphi.g
delphi-frontend/src/test/java/au/com/integradev/delphi/antlr/GrammarTest.java
delphi-frontend/src/test/resources/au/com/integradev/delphi/grammar/GreaterThanEqualAmbiguity.pas

This PR fixes a grammar ambiguity around adjacent `>` and `=` tokens. (Fixes #318)
We now create `>=` tokens during parsing by combining the `>`/`=` tokens, instead of combining them at the lexing stage.
(For consistently, we're doing this for "less than equal" tokens as well)
This allows us to only create `>=` tokens when we're parsing a binary expression.
As a result, we can now successfully parse code that looks like this:
```pas
const Foo: TArray<Byte>=[1, 2, 3];
```
Previously this would create a `>=` token in the middle and make everything fall over.

Fix parsing ambiguity around adjacent `>` and `=` tokens

---

delphi-checks/src/main/java/au/com/integradev/delphi/checks/RedundantJumpCheck.java
delphi-checks/src/test/java/au/com/integradev/delphi/checks/RedundantJumpCheckTest.java

This PR simplifies some code and adds some tests to improve coverage in the new `RedundantJumpCheck`.

Improve coverage in `RedundantJumpCheck`

---

delphi-checks/src/test/java/au/com/integradev/delphi/checks/DestructorWithoutInheritedCheckTest.java

This PR improves coverage in `DestructorWithoutInheritedCheck`, which previously had only 50% coverage.

Improve coverage in `DestructorWithoutInheritedCheck`

---

CHANGELOG.md
delphi-checks/src/main/java/au/com/integradev/delphi/checks/MixedNamesCheck.java
delphi-checks/src/test/java/au/com/integradev/delphi/checks/MixedNamesCheckTest.java

This PR adds a setting on MixedNames rule to ignore certain names.
This PR implements a suggestion I have for MixedNames rule. In my company, we have certain patterns in names, so in some cases it's suggested by the rule to comply with the definition, and ends up not being compliant with our pattern. I think it would be good to have a list for names to be ignored.
For example, sometimes the rules suggest to be WParam, and sometimes WPARAM, due to the definition. If we have a pattern to always be WParam, this addition could help to ignore WParam name, and don't raise any issues.
It's up to you to know if this is a desired feature or not.

Add an ignore list to MixedNames

---

CHANGELOG.md
delphi-checks/src/main/java/au/com/integradev/delphi/checks/IndexLastListElementCheck.java
delphi-checks/src/test/java/au/com/integradev/delphi/checks/IndexLastListElementCheckTest.java

This PR updates IndexLastListElement to ignore the left-hand side of expression statements. This is a current false-positive, since `TList.Last` is a function and is not eligible to be assigned to.

Fix IndexLastListElement issues on assignments and var/out

---

CHANGELOG.md
delphi-frontend/src/main/antlr3/au/com/integradev/delphi/antlr/Delphi.g

This PR fixes instances of  `IllegalArgumentException` being raised by the CPD executor on lines that end with `>=` or `<=`,, caused by file pointer errors.
`>=` and `<=` token positions were incorrect after token combination had occurred.
The solution is to adjust the token `line` and `charPositionInLine` as part of the combination step, where we previously only adjusted the token start/stop indices.

Fix file pointer errors around `>=` and `<=` tokens

---

delphi-frontend/src/main/antlr3/au/com/integradev/delphi/antlr/Delphi.g
its/src/projects/cpd-simple/src/CpdTest.pas

Token combination now creates a new token instead of mutating the last token in the group of combined tokens.
This was causing problems because the combined token would be reflected back to the original list of "raw tokens" returned by `DelphiFile::getTokens`, resulting in overlapping tokens being reported to the sonar API.
The mutability of the raw tokens is a point of brittleness that we could address, but it would have significant performance implications because it would involve constructing a copy of every token in every file.

Fix "tokens out of order" CPD errors around `>=` and `<=` tokens

---

CHANGELOG.md
delphi-checks/src/main/java/au/com/integradev/delphi/checks/LoopExecutingAtMostOnceCheck.java
delphi-checks/src/main/java/au/com/integradev/delphi/checks/RedundantJumpCheck.java
delphi-checks/src/main/java/au/com/integradev/delphi/utils/ControlFlowGraphUtils.java
delphi-checks/src/test/java/au/com/integradev/delphi/checks/LoopExecutingAtMostOnceCheckTest.java
delphi-checks/src/test/java/au/com/integradev/delphi/checks/RedundantJumpCheckTest.java
delphi-checks/src/test/java/au/com/integradev/delphi/utils/ControlFlowGraphUtilsTest.java
delphi-frontend/src/main/java/au/com/integradev/delphi/cfg/ControlFlowGraphDebug.java
delphi-frontend/src/main/java/au/com/integradev/delphi/cfg/ControlFlowGraphVisitor.java
delphi-frontend/src/main/java/au/com/integradev/delphi/cfg/api/Branch.java
delphi-frontend/src/main/java/au/com/integradev/delphi/cfg/api/Cases.java
delphi-frontend/src/main/java/au/com/integradev/delphi/cfg/api/Finally.java
delphi-frontend/src/main/java/au/com/integradev/delphi/cfg/block/BlockImpl.java
delphi-frontend/src/main/java/au/com/integradev/delphi/cfg/block/ProtoBlockFactory.java
delphi-frontend/src/test/java/au/com/integradev/delphi/cfg/ControlFlowGraphTest.java
delphi-frontend/src/test/java/au/com/integradev/delphi/cfg/checker/BlockChecker.java

This PR fixes various control flow graph bugs (which fixes #340). Additionally, a bug in `RedundantJumpCheck` has been fixed where nested try-finally blocks were erroneously raising issues.

Improve `RedundantJump` and fix bugs with control flow graph

---

CHANGELOG.md
delphi-checks/src/main/java/au/com/integradev/delphi/checks/VisibilityKeywordIndentationCheck.java
delphi-checks/src/test/java/au/com/integradev/delphi/checks/VisibilityKeywordIndentationCheckTest.java

This PR fixes false positives in `VisibilityKeywordIndentation`.
The rule was trying to match to the indentation of the line where the `TypeNode` began.
The thing is, we're actually more interesting in the top-level type declaration.
Example:
```pas
type
Foo = // we care about the indentation of this line
class(TObject) // but the rule was using this one
public // <-- FP will be raised here.
procedure Bar;
end;
```

Fix FPs on wrapped type headers in `VisibilityKeywordIndentationCheck`

---

CHANGELOG.md
delphi-checks/src/main/java/au/com/integradev/delphi/checks/UnusedTypeCheck.java
delphi-checks/src/test/java/au/com/integradev/delphi/checks/UnusedTypeCheckTest.java

This PR adds an exclusion to `UnusedType` for types that are annotated with custom attributes.
It's unclear why this wasn't already the case, as the same exclusion is already present in `UnusedRoutine`, `UnusedProperty`, and `UnusedField`.

Exclude types annotated with attributes in `UnusedType`

---

CHANGELOG.md
delphi-frontend/src/main/java/au/com/integradev/delphi/compiler/PredefinedConditionals.java
delphi-frontend/src/test/java/au/com/integradev/delphi/compiler/PredefinedConditionalsTest.java

This PR adds support for the undocumented `WEAK_NATIVEINT` predefined conditional symbol.
It's defined from Delphi 12 onward.
This was discovered due to a strange false positive on Delphi 12:
It turns out that the Delphi 12 RTL still declares `TNativeIntHelper` and gates it behind this `WEAK_NATIVEINT` symbol.
Without the symbol defined, the analyzer would see the `TNativeIntHelper` record helper defined and overriding `TIntegerHelper` since (as weak aliases) they are the same type now.
This caused the analyzer to think that `TNativeIntHelper.Parse` was being called, which (of course) returns a `NativeInt` and confuses the `PlatformDependentTruncation` check.

Define the `WEAK_NATIVEINT` conditional on Delphi 12+

---

CHANGELOG.md
delphi-checks/src/main/java/au/com/integradev/delphi/checks/TrailingWhitespaceCheck.java
delphi-checks/src/test/java/au/com/integradev/delphi/checks/TrailingWhitespaceCheckTest.java

This PR improves `TrailingWhitespace` to detect trailing whitespace within comments.
An incidental change is that we're now also detecting whitespace more accurately by matching characters in range `0x00`-`0x20`. This matches the compiler's behavior.

Detect trailing whitespace within comments in `TrailingWhitespace`

---

CHANGELOG.md
delphi-frontend/src/main/java/au/com/integradev/delphi/type/intrinsic/IntrinsicReturnType.java
delphi-frontend/src/main/java/au/com/integradev/delphi/type/intrinsic/IntrinsicsInjector.java
delphi-frontend/src/test/java/au/com/integradev/delphi/type/intrinsic/IntrinsicReturnTypeTest.java

This PR adds support for 4 undocumented intrinsics that are usable within `varargs` routines.
Signatures for these intrinsics can be found in `System`:
```pas
// procedure VarArgStart(var ArgList: TVarArgList);
// function  VarArgGetValue(var ArgList: TVarArgList; ArgType: Type): ArgType;
// procedure VarArgCopy(var DestArgList, SrcArgList: TVarArgList);
// procedure VarArgEnd(var ArgList: TVarArgList);
```
We can't easily inject intrinsics with specific concrete types like `System.TVarArgList`, so I've opted for the "good enough" solution of using untyped parameters for these. I can't see any obvious way for this to result in a less inaccurate analysis (on source code that successfully compiles).
* [How to create a Delphi variadic method similar to Write/Writeln without requiring …

Add support for undocumented `varargs` intrinsics

---

CHANGELOG.md
delphi-checks/src/main/java/au/com/integradev/delphi/checks/CheckList.java
delphi-checks/src/main/java/au/com/integradev/delphi/checks/ParsingErrorCheck.java
delphi-checks/src/main/resources/org/sonar/l10n/delphi/rules/community-delphi/ParsingError.html
delphi-checks/src/main/resources/org/sonar/l10n/delphi/rules/community-delphi/ParsingError.json
delphi-checks/src/test/java/au/com/integradev/delphi/checks/CheckTestNameTest.java
delphi-frontend/src/main/antlr3/au/com/integradev/delphi/antlr/Delphi.g
delphi-frontend/src/main/java/au/com/integradev/delphi/file/DelphiFile.java
sonar-delphi-plugin/src/main/java/au/com/integradev/delphi/DelphiSensor.java
sonar-delphi-plugin/src/test/java/au/com/integradev/delphi/DelphiSensorTest.java

This PR implements a check to flag files where parsing failures have occurred.
The official analyzers from SonarSource have similar rules. Like them, I've opted not to put it in the default quality profile.
Closes #301.

Implement `ParsingError` check

---

CHANGELOG.md
delphi-frontend/src/main/java/au/com/integradev/delphi/type/intrinsic/IntrinsicsInjector.java

This PR fixes an overload resolution issue involving the `Copy` intrinsic.
We didn't previously register the variant overload `Copy(Variant, Integer, Integer)`.
This caused overload resolution failures when calling `Copy` on a variant value.

Fix overload resolution failures on the variant overload of `Copy`

---

CHANGELOG.md
delphi-frontend/src/main/antlr3/au/com/integradev/delphi/antlr/Delphi.g
delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/ast/token/DelphiTokenImpl.java
delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/ast/token/IncludeToken.java
delphi-frontend/src/main/java/au/com/integradev/delphi/file/DelphiFile.java
delphi-frontend/src/main/java/au/com/integradev/delphi/preprocessor/DelphiPreprocessor.java
delphi-frontend/src/main/java/au/com/integradev/delphi/preprocessor/PreprocessorException.java
delphi-frontend/src/main/java/au/com/integradev/delphi/preprocessor/directive/CompilerDirectiveParserImpl.java
delphi-frontend/src/main/java/au/com/integradev/delphi/utils/LocatableException.java
delphi-frontend/src/test/java/au/com/integradev/delphi/preprocessor/DelphiPreprocessorTest.java
sonar-delphi-plugin/src/main/java/au/com/integradev/delphi/DelphiSensor.java
sonar-delphi-plugin/src/test/java/au/com/integradev/delphi/DelphiSensorTest.java

Line information was incorrect or incomplete in some cases:
- within include files
- within compiler directives
- when include processing fails due to self-referencing include files
This was discovered due to the new `ParsingError` check triggering file pointer errors when trying to raise issues on included tokens.

Improve reporting of preprocessor-related parsing failures

---

CHANGELOG.md
delphi-checks-testkit/src/main/java/au/com/integradev/delphi/builders/AbstractDelphiTestFile.java
delphi-checks-testkit/src/main/java/au/com/integradev/delphi/checks/verifier/CheckVerifierImpl.java
delphi-frontend/src/main/java/au/com/integradev/delphi/preprocessor/DelphiPreprocessor.java
delphi-frontend/src/main/java/au/com/integradev/delphi/preprocessor/DelphiPreprocessorFactory.java
delphi-frontend/src/main/java/au/com/integradev/delphi/preprocessor/directive/expression/Expressions.java
delphi-frontend/src/test/java/au/com/integradev/delphi/antlr/GrammarTest.java
delphi-frontend/src/test/java/au/com/integradev/delphi/cfg/ControlFlowGraphTest.java
delphi-frontend/src/test/java/au/com/integradev/delphi/executor/DelphiMasterExecutorTest.java
delphi-frontend/src/test/java/au/com/integradev/delphi/executor/DelphiMetricsExecutorTest.java
delphi-frontend/src/test/java/au/com/integradev/delphi/executor/DelphiSymbolTableExecutorTest.java
delphi-frontend/src/test/java/au/com/integradev/delphi/executor/DelphiTokenExecutorTest.java
delphi-frontend/src/test/java/au/com/integradev/delphi/file/DelphiFileTest.java
delphi-frontend/src/test/java/au/com/integradev/delphi/preprocessor/DelphiPreprocessorTest.java
delphi-frontend/src/test/java/au/com/integradev/delphi/preprocessor/directive/expression/ExpressionsTest.java
delphi-frontend/src/test/java/au/com/integradev/delphi/reporting/QuickFixEditTest.java
delphi-frontend/src/test/java/au/com/integradev/delphi/symbol/SymbolTableBuilderTest.java
delphi-frontend/src/test/java/au/com/integradev/delphi/utils/files/DelphiFileUtils.java
sonar-delphi-plugin/src/main/java/au/com/integradev/delphi/DelphiSensor.java

This PR adds support for the `CompilerVersion` constant in compiler directive expressions.
It also improves the evaluation of:
- `System.True`
- `System.False`
- `System.Defined`
- `System.SizeOf`
This is more of a bolt-on hack than anything. It's worth doing for now because `CompilerVersion` is frequently used in directive expressions and can be statically known from configuration (`sonar.delphi.compilerVersion`).
For more accurate evaluation of compiler directive expressions, we're still blocked on #261.

Add support for `CompilerVersion` in compiler directive expressions

---

CHANGELOG.md
delphi-checks/src/main/java/au/com/integradev/delphi/checks/TabulationCharacterCheck.java
delphi-checks/src/test/java/au/com/integradev/delphi/checks/TabulationCharacterCheckTest.java
delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/ast/token/DelphiTokenImpl.java
delphi-tokens-generator-maven-plugin/src/main/java/au/com/integradev/delphi/DelphiTokensGenerator.java
delphi-tokens-generator-maven-plugin/src/test/java/au/com/integradev/delphi/DelphiTokensGeneratorTest.java

This PR adds handling for multiline strings in the `TabulationCharacter` rule.
We now raise issues on multiline strings using tabs for indentation, where we previously only looked at whitespace tokens.
I've also fixed a couple bugs that came up along the way:
- The `DelphiTokenType` generated class was going to the wrong path.
- File position for multiline strings were being calculated incorrectly (as if they weren't multiline tokens).

Raise issues for tab-indented multiline strings in `TabulationCharacter`

---

delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/ast/token/IncludeToken.java

This constructor became unused with #356 when we started creating `IncludeToken` instances at lex-time.

Remove unused `IncludeToken` constructor

---

.github/workflows/build.yml
.github/workflows/sonar.yml

It's been days since SonarSource released 25.4.0.105899 to maven central, and the `sonarqube-application` zip artifact is still missing. This is causing our integration tests to fail because we always pass `LATEST_RELEASE` to the orchestrator.
This PR introduces a repository-level `ORCHESTRATOR_SONAR_VERSION` variable which can override the SonarQube version we use in integration tests.
See:
- [25.4.0.105899 is missing on Maven Central](https://community.sonarsource.com/t/25-4-0-105899-is-missing-on-maven-central/138625)

Add `ORCHESTRATOR_SONAR_VERSION` override for integration tests

---

CHANGELOG.md
delphi-checks/src/test/java/au/com/integradev/delphi/checks/UnusedPropertyCheckTest.java
delphi-checks/src/test/java/au/com/integradev/delphi/checks/UnusedRoutineCheckTest.java
delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/ast/node/ForInStatementNodeImpl.java
delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/ast/visitors/DependencyAnalysisVisitor.java
delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/ast/visitors/SymbolAssociationVisitor.java
delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/ast/visitors/SymbolTableVisitor.java
delphi-frontend/src/main/java/au/com/integradev/delphi/symbol/declaration/VariableNameDeclarationImpl.java
delphi-frontend/src/main/java/au/com/integradev/delphi/symbol/occurrence/EnumeratorOccurrenceImpl.java
delphi-frontend/src/main/java/au/com/integradev/delphi/symbol/resolve/NameResolutionHelper.java
delphi-frontend/src/main/java/au/com/integradev/delphi/symbol/scope/FileScopeImpl.java
delphi-frontend/src/main/java/org/sonar/plugins/communitydelphi/api/ast/ForInStatementNode.java
delphi-frontend/src/main/java/org/sonar/plugins/communitydelphi/api/symbol/EnumeratorOccurrence.java
delphi-frontend/src/test/resources/au/com/integradev/delphi/symbol/dependencies/imports/UnitWithGetEnumeratorForTObject.pas

There are a few magic enumerator-related declarations:
- `GetEnumerator` enumerable method
- `MoveNext` enumerator method
- `Current` enumerator property
These are implicitly used by for-in loops, but we weren't previously encoding that information in the symbol table.
As a result, the `Unused*` rules were raising issues on them.
I've also fixed a symbol table visitor bug causing name resolution failures in legacy initialization sections, which came up while testing the changes around enumerator usages.

Fix FPs around enumerators in `UnusedRoutine` and `UnusedProperty`

---

CHANGELOG.md
delphi-checks/src/main/java/au/com/integradev/delphi/checks/UnusedTypeCheck.java
delphi-checks/src/test/java/au/com/integradev/delphi/checks/UnusedTypeCheckTest.java

This PR fixes false positives in the `UnusedType` rule around enums.
If an enum type is never referenced by name, that doesn't mean the whole type is unused.
We now also check if any of its values are used.

Fix FPs around enums that are never referenced by name in `UnusedType`

---

CHANGELOG.md
delphi-frontend/src/main/antlr3/au/com/integradev/delphi/antlr/Delphi.g
delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/ast/node/TypeOfTypeNodeImpl.java
delphi-frontend/src/main/java/org/sonar/plugins/communitydelphi/api/ast/TypeOfTypeNode.java
delphi-frontend/src/test/java/au/com/integradev/delphi/executor/DelphiSymbolTableExecutorTest.java
delphi-frontend/src/test/resources/au/com/integradev/delphi/symbol/classReferences/TypeOf.pas

This PR:
- fixes the `ClassCastException` in `TypeOfTypeNode::createType`
- models the type as a class reference type (like `class of`)
Fixes #361.

Fix analysis errors around `type of` types

---

pom.xml

See: https://community.sonarsource.com/t/fail-to-load-versions-of-org-sonarsource-sonarqube-sonar-application/138865

Disable integration tests until SonarSource fixes the orchestrator

---

.github/workflows/format.yml
README.md
delphi-frontend/src/main/java/au/com/integradev/delphi/msbuild/condition/BinaryExpression.java
pom.xml

This also bumps our minimum JDK requirement to 17, as it's a requirement starting from google-java-format 1.25.0.

Upgrade google-java-format to 1.26.0

---

CHANGELOG.md
delphi-checks/src/main/java/au/com/integradev/delphi/checks/CheckList.java
delphi-checks/src/main/java/au/com/integradev/delphi/checks/ExhaustiveEnumCaseCheck.java
delphi-checks/src/main/resources/org/sonar/l10n/delphi/rules/community-delphi/ExhaustiveEnumCase.html
delphi-checks/src/main/resources/org/sonar/l10n/delphi/rules/community-delphi/ExhaustiveEnumCase.json
delphi-checks/src/test/java/au/com/integradev/delphi/checks/ExhaustiveEnumCaseCheckTest.java

Fixes #98. I haven't added the rule to the default quality profile since it may be frustrating for existing codebases.

Add check for exhaustive `case` statements over enums

---

CHANGELOG.md
delphi-checks/src/main/java/au/com/integradev/delphi/checks/CheckList.java
delphi-checks/src/main/java/au/com/integradev/delphi/checks/IterationPastHighBoundCheck.java
delphi-checks/src/main/resources/org/sonar/l10n/delphi/rules/community-delphi/IterationPastHighBound.html
delphi-checks/src/main/resources/org/sonar/l10n/delphi/rules/community-delphi/IterationPastHighBound.json
delphi-checks/src/main/resources/org/sonar/l10n/delphi/rules/community-delphi/Sonar_way_profile.json
delphi-checks/src/test/java/au/com/integradev/delphi/checks/IterationPastHighBoundCheckTest.java

Fixes #95. I haven't added this to the Sonar way quality profile, but it probably could be added depending on how noisy it is. I'll run some tests and see.

Add check for array iterations where the high bound is out of range

---

CHANGELOG.md
delphi-checks/src/main/java/au/com/integradev/delphi/checks/CheckList.java
delphi-checks/src/main/java/au/com/integradev/delphi/checks/ExplicitBitwiseNotCheck.java
delphi-checks/src/main/resources/org/sonar/l10n/delphi/rules/community-delphi/ExplicitBitwiseNot.html
delphi-checks/src/main/resources/org/sonar/l10n/delphi/rules/community-delphi/ExplicitBitwiseNot.json
delphi-checks/src/main/resources/org/sonar/l10n/delphi/rules/community-delphi/Sonar_way_profile.json
delphi-checks/src/test/java/au/com/integradev/delphi/checks/ExplicitBitwiseNotCheckTest.java

Fixes #97. This rule works by highlighting any `in` binary expression with one operand being a bitwise `not`. ~I haven't added it to the default quality profile~ I have now added it to the default quality profile, since it is a rare and admittedly confusing case.

Add check for ambiguous bitwise not operations

---

pom.xml

The latest version of orchestrator fixes a bug where maven metadata couldn't be parsed, which was failing our integration tests before. (see #366)

Upgrade orchestrator to 5.6.1.2597 and restore integration tests

---

delphi-frontend/src/main/java/au/com/integradev/delphi/msbuild/expression/ExpressionEvaluator.java

This PR does some minor QA in the recently-added `ExpressionEvaluator`.
I've also enabled the "Control structures should use curly braces" rule on SonarCloud. It shouldn't raise any issues, as the rest of the codebase consistently uses curly braces.

Tidy up `ExpressionEvaluator`

---

CHANGELOG.md
delphi-frontend/src/main/java/au/com/integradev/delphi/symbol/resolve/NameResolutionHelper.java
delphi-frontend/src/test/java/au/com/integradev/delphi/executor/DelphiSymbolTableExecutorTest.java
delphi-frontend/src/test/resources/au/com/integradev/delphi/symbol/Properties.pas

When a property has an `index` specifier, its `read` specifier must be a function with an `Integer` final argument, and its `write` specifier must be a procedure with an `Integer` second-last argument. We were not previously modelling this behaviour, causing `read` and `write` specifier methods to fail to resolve when an `index` property is present.

Disambiguate index property read/write methods correctly

---

CHANGELOG.md
delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/ast/node/ArrayExpressionNodeImpl.java
delphi-frontend/src/main/java/au/com/integradev/delphi/symbol/resolve/NameResolutionHelper.java
delphi-frontend/src/test/java/au/com/integradev/delphi/executor/DelphiSymbolTableExecutorTest.java
delphi-frontend/src/test/resources/au/com/integradev/delphi/symbol/RoutineReferenceAssignedToProcedural.pas

This PR improves name resolution on routine references in:
- assignment to inline `var`/`const` declarations
- assignment to standard `var` declarations
- assignment to standard typed `const` declarations
- constant arrays
- This required improvements to type resolution for constant array expressions.
Multidimensional constant arrays are especially improved, as their subarrays couldn't **ever** resolve properly before.

Fix various name resolution errors around routine references

---

CHANGELOG.md
delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/ast/node/GenericDefinitionNodeImpl.java
delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/ast/node/TypeParameterNodeImpl.java
delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/ast/visitors/SymbolTableVisitor.java
delphi-frontend/src/main/java/au/com/integradev/delphi/symbol/resolve/ExpressionTypeResolver.java
delphi-frontend/src/main/java/au/com/integradev/delphi/symbol/resolve/NameResolver.java
delphi-frontend/src/main/java/au/com/integradev/delphi/type/generic/TypeSpecializationContextImpl.java
delphi-frontend/src/main/java/org/sonar/plugins/communitydelphi/api/ast/TypeParameterNode.java
delphi-frontend/src/test/java/au/com/integradev/delphi/executor/DelphiSymbolTableExecutorTest.java
delphi-frontend/src/test/resources/au/com/integradev/delphi/symbol/classReferences/ConstructorTypeResolution.pas
delphi-frontend/src/test/resources/au/com/integradev/delphi/symbol/generics/Constraint.pas
delphi-frontend/src/test/resources/au/com/integradev/delphi/symbol/typeResolution/Casts.pas

This PR fixes:
- Name resolution failures around generic routine invocations, mostly because we were not specializing type constraints
- Type resolution failures on `as` casts where the type expression is a function (e.g. `GetFooClass`)
- Type resolution failures on constructors for class reference types (e.g. `TFooClass.Create`, which creates a `TFoo`)

Fix various type resolution failures

---

CHANGELOG.md
delphi-checks/src/main/java/au/com/integradev/delphi/checks/ForbiddenRoutineCheck.java
delphi-checks/src/main/java/au/com/integradev/delphi/checks/InterfaceGuidCheck.java
delphi-checks/src/main/java/au/com/integradev/delphi/checks/MixedNamesCheck.java
delphi-checks/src/main/java/au/com/integradev/delphi/checks/RoutineNameCheck.java
delphi-frontend/src/main/antlr3/au/com/integradev/delphi/antlr/Delphi.g
delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/ast/node/AttributeGroupNodeImpl.java
delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/ast/node/AttributeListNodeImpl.java
delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/ast/node/AttributeNodeImpl.java
delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/ast/node/InterfaceGuidNodeImpl.java
delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/ast/node/InterfaceTypeNodeImpl.java
delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/ast/visitors/DelphiParserVisitor.java
delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/ast/visitors/SymbolTableVisitor.java
delphi-frontend/src/main/java/au/com/integradev/delphi/symbol/resolve/ExpressionTypeResolver.java
delphi-frontend/src/main/java/au/com/integradev/delphi/symbol/resolve/NameResolutionHelper.java
delphi-frontend/src/main/java/au/com/integradev/delphi/symbol/resolve/NameResolver.java
delphi-frontend/src/main/java/org/sonar/plugins/communitydelphi/api/ast/AttributeNode.java
delphi-frontend/src/main/java/org/sonar/plugins/communitydelphi/api/ast/InterfaceGuidNode.java
delphi-frontend/src/main/java/org/sonar/plugins/communitydelphi/api/ast/InterfaceTypeNode.java
delphi-frontend/src/test/java/au/com/integradev/delphi/executor/DelphiSymbolTableExecutorTest.java
delphi-frontend/src/test/resources/au/com/integradev/delphi/symbol/Guid.pas

This PR fixes a significant grammar ambiguity between attributes and interface GUIDs.
Consider the following:
```pas
const
FooAttribute = class(TCustomAttribute)
end;
TBar = interface
[Foo]
procedure Baz;
end;
```
At the moment, the grammar interprets `[Foo]` as a GUID containing constant expression `Foo`.
It should actually be interpreted as a custom attribute on the `Baz` procedure.
In the process of resolving this ambiguity, I discovered some awful details.
```pas
const
FooAttribute = class(TCustomAttribute)
end;
TBar = interface
[Foo, '{4E89BDD0-B67C-4B4D-86E6-2C0D1DC7B237']
procedure Baz;
end;
```
This applies `FooAttribute` to `Baz` and applies the GUID to `TBar`.
Based on this, it's clear that the custom attribute and GUID syntax are really one and the same, and the ambiguity was a …

Fix grammar ambiguity between attributes and interface GUIDs

---

CHANGELOG.md
delphi-checks-testkit/src/main/java/au/com/integradev/delphi/checks/verifier/CheckVerifierImpl.java
delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/ast/visitors/SymbolTableVisitor.java
delphi-frontend/src/main/java/au/com/integradev/delphi/symbol/scope/SystemScopeImpl.java
delphi-frontend/src/main/java/au/com/integradev/delphi/type/factory/TypeFactoryImpl.java
delphi-frontend/src/main/java/au/com/integradev/delphi/type/intrinsic/IntrinsicConstant.java
delphi-frontend/src/main/java/au/com/integradev/delphi/type/intrinsic/IntrinsicRoutine.java
delphi-frontend/src/main/java/au/com/integradev/delphi/type/intrinsic/IntrinsicsInjector.java
delphi-frontend/src/main/java/org/sonar/plugins/communitydelphi/api/type/IntrinsicType.java
delphi-frontend/src/test/java/au/com/integradev/delphi/executor/DelphiSymbolTableExecutorTest.java
delphi-frontend/src/test/resources/au/com/integradev/delphi/symbol/intrinsics/GetTypeKindIntrinsic.pas
delphi-frontend/src/test/resources/au/com/integradev/delphi/symbol/intrinsics/VarArgIntrinsics.pas

This PR does a few things.
Improves the way we handle intrinsic routines by:
- deferring their injection into `System` until the end of the `interface` section
- resolving references to public `System` types in their parameter lists and return types
Adds support for:
- `AtomicCmpExchange128`
- `GetTypeKind`
- `OpenString` type
Improves signatures of:
- `IsManagedType`
- `VarArgStart`
- `VarArgGetValue`
- `VarArgCopy`
- `VarArgEnd`

Improve handling for various intrinsics

---

delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/ast/visitors/SymbolTableVisitor.java
delphi-frontend/src/main/java/au/com/integradev/delphi/symbol/scope/SystemScopeImpl.java
delphi-frontend/src/main/java/org/sonar/plugins/communitydelphi/api/ast/InterfaceGuidNode.java

This PR fixes 2 sonar issues raised by recent PRs.

Fix sonar issues

---

delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/ast/node/AttributeNodeImpl.java
delphi-frontend/src/main/java/au/com/integradev/delphi/antlr/ast/node/InterfaceTypeNodeImpl.java
delphi-frontend/src/test/java/au/com/integradev/delphi/antlr/ast/node/AttributeNodeImplTest.java
delphi-frontend/src/test/java/au/com/integradev/delphi/antlr/ast/node/InterfaceTypeNodeImplTest.java
delphi-frontend/src/test/java/au/com/integradev/delphi/utils/files/DelphiFileUtils.java

This PR improves test coverage in `AttributeNodeImpl` and `InterfaceTypeNodeImpl`.

Improve test coverage in new AST code

---

README.md

While DelphiLint prominently references SonarDelphi, we don't have any reference to DelphiLint on the SonarDelphi readme. Considering the overlap in interests is pretty high, we should add a helpful note to the readme pointing people to DelphiLint.

Reference DelphiLint in the README

---

CHANGELOG.md
delphi-frontend/src/main/java/au/com/integradev/delphi/symbol/resolve/InvocationResolver.java
delphi-frontend/src/test/java/au/com/integradev/delphi/symbol/resolve/InvocationResolverTest.java

`Variant` -> `Double` and `Variant` -> `Extended` were being treated as equally good conversions on toolchains where `Double` and `Extended` are the same size, such as `DCC64`.

Fix ambiguous type comparisons from variants to real types 

---

.github/workflows/release.yml
pom.xml

This PR unblocks the July release by migrating from OSSRH (EOL) to the Central Portal.
Repository secrets have already been updated.
Successful run here (including staging/validation, but of course not publishing):
https://github.com/cirras/sonar-delphi/actions/runs/16017755532/job/45187583849

Migrate from OSSRH to the Central Portal

---

CHANGELOG.md
delphi-checks/src/main/java/au/com/integradev/delphi/checks/EmptyBlockCheck.java
delphi-checks/src/main/resources/org/sonar/l10n/delphi/rules/community-delphi/EmptyBlock.html
delphi-checks/src/test/java/au/com/integradev/delphi/checks/EmptyBlockCheckTest.java

Fixes #221. 
I considered updating EmptyRoutine and SwallowedException to also ignore all blocks with comments, but I didn't in the end because I decided they had higher-level reasoning than just syntax-level "this block is unnecessary", and so we probably want to forbid those bad patterns regardless of whether there's a comment or not. Happy to hear other views.

Ignore all blocks with comments in EmptyBlock

---

CHANGELOG.md
delphi-checks/src/main/java/au/com/integradev/delphi/checks/CheckList.java
delphi-checks/src/main/java/au/com/integradev/delphi/checks/ObjectPassedAsInterfaceCheck.java
delphi-checks/src/main/resources/org/sonar/l10n/delphi/rules/community-delphi/ObjectPassedAsInterface.html
delphi-checks/src/main/resources/org/sonar/l10n/delphi/rules/community-delphi/ObjectPassedAsInterface.json
delphi-checks/src/main/resources/org/sonar/l10n/delphi/rules/community-delphi/Sonar_way_profile.json
delphi-checks/src/test/java/au/com/integradev/delphi/checks/ObjectPassedAsInterfaceCheckTest.java

Implement `ObjectPassedAsInterface` check
